const std = @import("std");
const machine = @import("machine.zig");
const StateProgram = @import("program.zig").Program;
const workspace = @import("../../common/workspace.zig");

pub fn writeTbMachine(
    io: std.Io,
    allocator: std.mem.Allocator,
    program: StateProgram,
    output_name: []const u8,
) !void {
    try workspace.ensureNamespace(io, program);

    const output_path = try workspace.artifactPath(
        allocator,
        program,
        output_name,
    );
    defer allocator.free(output_path);

    var file = try std.Io.Dir.cwd().createFile(io, output_path, .{});
    defer file.close(io);

    var buffer: [32768]u8 = undefined;
    var writer = file.writer(io, &buffer);

    try write(&writer.interface, program.machine);
    try writer.interface.flush();
}

pub fn write(writer: anytype, m: machine.Machine) !void {
    const event_bits = bitWidth(m.events.len);
    const state_bits = bitWidth(m.states.len);

    // header
    try writer.print(
        \\// generated by MatterScript
        \\// machine: {s}
        \\// DO NOT EDIT — regenerate by running matterscript on the .ms.fsm source
        \\#include "V{s}.h"
        \\#include "verilated.h"
        \\#include <cstdio>
        \\#include <cassert>
        \\
        \\
    , .{ m.name, m.name });

    // event constants
    try writer.print("// event encoding\n", .{});
    var ev_buf: [64]u8 = undefined;
    for (m.events, 0..) |e, i| {
        const bits = binStr(&ev_buf, i, event_bits);
        try writer.print(
            "#define EV_{s} 0b{s}\n",
            .{ e.name, bits },
        );
    }
    try writer.print("\n", .{});

    // state constants
    try writer.print("// state encoding\n", .{});
    var st_buf: [64]u8 = undefined;
    for (m.states, 0..) |s, i| {
        const bits = binStr(&st_buf, i, state_bits);
        try writer.print(
            "#define ST_{s} 0b{s}\n",
            .{ s.name, bits },
        );
    }
    try writer.print("\n", .{});

    // dut and cycle globals
    try writer.print(
        \\static V{s}* dut;
        \\static int cycle = 0;
        \\
        \\static void tick() {{
        \\    dut->clk = 0; dut->eval();
        \\    dut->clk = 1; dut->eval();
        \\    cycle++;
        \\}}
        \\
        \\static void reset() {{
        \\    dut->rst = 1;
        \\    dut->event_in = 0;
        \\    tick();
        \\    dut->rst = 0;
        \\}}
        \\
        \\static void send_event(int ev) {{
        \\    dut->event_in = ev;
        \\    tick();
        \\    dut->event_in = 0;
        \\}}
        \\
        \\static void expect_state(int expected, const char* name) {{
        \\    if (dut->state_out != expected) {{
        \\        printf("FAIL at cycle %d: expected %s (%d), got %d\n",
        \\               cycle, name, expected, (int)dut->state_out);
        \\        exit(1);
        \\    }}
        \\    printf("  cycle %2d: state = %s\n", cycle, name);
        \\}}
        \\
        \\
    , .{m.name});

    // main
    try writer.print(
        \\int main(int argc, char** argv) {{
        \\    Verilated::commandArgs(argc, argv);
        \\    dut = new V{s};
        \\
        \\    printf("{s} FSM simulation\n");
        \\    printf("
    , .{ m.name, m.name });

    // print separator line sized to machine name
    for (0..m.name.len + 16) |_| try writer.print("-", .{});
    try writer.print(
        \\
        \\");
        \\
        \\    // reset — lands in first state
        \\    reset();
        \\
    , .{});

    // assert reset state
    if (m.states.len > 0) {
        try writer.print(
            "    expect_state(ST_{s}, \"{s}\");\n\n",
            .{ m.states[0].name, m.states[0].name },
        );
    }

    // walk the happy path: follow transitions in declaration order
    // build a simple chain by finding the first transition out of each state
    try writer.print("    // happy path — follow transitions in declaration order\n", .{});
    var current = if (m.states.len > 0) m.states[0].name else "";
    var steps: usize = 0;
    while (steps < m.transitions.len) : (steps += 1) {
        // find first transition from current state
        var found = false;
        for (m.transitions) |t| {
            if (std.mem.eql(u8, t.from, current)) {
                try writer.print(
                    "    send_event(EV_{s});\n",
                    .{t.on},
                );
                try writer.print(
                    "    expect_state(ST_{s}, \"{s}\");\n\n",
                    .{ t.to, t.to },
                );
                current = t.to;
                found = true;
                break;
            }
        }
        if (!found) break;
    }

    // sink state check: verify terminal state ignores events
    try writer.print("    // terminal state should ignore all events\n", .{});
    if (m.events.len > 0) {
        try writer.print(
            "    send_event(EV_{s});\n",
            .{m.events[0].name},
        );
        try writer.print(
            "    expect_state(ST_{s}, \"{s} (held)\");\n\n",
            .{ current, current },
        );
    }

    // footer
    try writer.print(
        \\    printf("
    , .{});
    for (0..m.name.len + 16) |_| try writer.print("-", .{});
    try writer.print(
        \\
        \\");
        \\    printf("PASS — all transitions correct\n");
        \\
        \\    dut->final();
        \\    delete dut;
        \\    return 0;
        \\}}
        \\
    , .{});
}

fn binStr(buf: []u8, val: usize, width: usize) []u8 {
    var i: usize = 0;
    while (i < width) : (i += 1) {
        const bit = (val >> @intCast(width - 1 - i)) & 1;
        buf[i] = if (bit == 1) '1' else '0';
    }
    return buf[0..width];
}

fn bitWidth(n: usize) usize {
    if (n <= 1) return 1;
    var bits: usize = 0;
    var val: usize = n - 1;
    while (val > 0) : (val >>= 1) {
        bits += 1;
    }
    return bits;
}
