const std = @import("std");
const machine = @import("machine.zig");
const StateProgram = @import("program.zig").Program;
const workspace = @import("../../common/workspace.zig");

pub fn writeVhdlMachine(
    io: std.Io,
    allocator: std.mem.Allocator,
    program: StateProgram,
    output_name: []const u8,
) !void {
    try workspace.ensureNamespace(io, program);

    const output_path = try workspace.artifactPath(
        allocator,
        program,
        output_name,
    );
    defer allocator.free(output_path);

    var file = try std.Io.Dir.cwd().createFile(io, output_path, .{});
    defer file.close(io);

    var buffer: [16384]u8 = undefined;
    var writer = file.writer(io, &buffer);

    try write(&writer.interface, program.machine);
    try writer.interface.flush();
}

pub fn write(writer: anytype, m: machine.Machine) !void {
    const event_bits = bitWidth(m.events.len);
    const state_bits = bitWidth(m.states.len);

    // header
    try writer.print(
        \\-- generated by MatterScript
        \\-- machine: {s}
        \\library ieee;
        \\use ieee.std_logic_1164.all;
        \\
        \\
    , .{m.name});

    // entity
    try writer.print("entity {s} is\n", .{m.name});
    try writer.print(
        \\  port(
        \\    clk       : in  std_logic;
        \\    rst       : in  std_logic;
        \\
    , .{});
    try writer.print(
        "    event_in  : in  std_logic_vector({d} downto 0);\n",
        .{event_bits - 1},
    );
    try writer.print(
        "    state_out : out std_logic_vector({d} downto 0)\n",
        .{state_bits - 1},
    );
    try writer.print(
        \\  );
        \\end {s};
        \\
        \\
    , .{m.name});

    // architecture header
    try writer.print("architecture rtl of {s} is\n", .{m.name});

    // state type enum
    try writer.print("  type state_t is (", .{});
    for (m.states, 0..) |s, i| {
        if (i > 0) try writer.print(", ", .{});
        try writer.print("{s}", .{s.name});
    }
    try writer.print(");\n", .{});

    // event constants — use helper since fmt width must be comptime
    try writer.print("\n", .{});
    var ev_bits_buf: [64]u8 = undefined;
    for (m.events, 0..) |e, i| {
        const bits = binStr(&ev_bits_buf, i, event_bits);
        try writer.print(
            "  constant EV_{s} : std_logic_vector({d} downto 0) := \"{s}\";\n",
            .{ e.name, event_bits - 1, bits },
        );
    }

    try writer.print(
        \\
        \\  signal current_state : state_t;
        \\  signal next_state    : state_t;
        \\begin
        \\
        \\  -- registered state
        \\  process(clk, rst) begin
        \\    if rst = '1' then
        \\
    , .{});

    // reset to first state
    if (m.states.len > 0) {
        try writer.print(
            "      current_state <= {s};\n",
            .{m.states[0].name},
        );
    }

    try writer.print(
        \\    elsif rising_edge(clk) then
        \\      current_state <= next_state;
        \\    end if;
        \\  end process;
        \\
        \\  -- combinational next state logic
        \\  process(current_state, event_in) begin
        \\    next_state <= current_state;
        \\    case current_state is
        \\
    , .{});

    // transition logic per state
    for (m.states) |s| {
        try writer.print("      when {s} =>\n", .{s.name});

        var has_transition = false;
        for (m.transitions) |t| {
            if (std.mem.eql(u8, t.from, s.name)) {
                try writer.print(
                    "        if event_in = EV_{s} then next_state <= {s}; end if;\n",
                    .{ t.on, t.to },
                );
                has_transition = true;
            }
        }
        if (!has_transition) {
            try writer.print("        null;\n", .{});
        }
    }

    try writer.print(
        \\    end case;
        \\  end process;
        \\
        \\  -- state output encoding
        \\  with current_state select
        \\
    , .{});

    // state output: with/select single assignment — only one <= for the whole statement
    var st_bits_buf: [64]u8 = undefined;
    for (m.states, 0..) |s, i| {
        const bits = binStr(&st_bits_buf, i, state_bits);
        if (i == 0) {
            try writer.print(
                "    state_out <= \"{s}\" when {s},\n",
                .{ bits, s.name },
            );
        } else {
            try writer.print(
                "                 \"{s}\" when {s},\n",
                .{ bits, s.name },
            );
        }
    }
    const zero_bits = binStr(&st_bits_buf, 0, state_bits);
    try writer.print(
        "                 \"{s}\" when others;\n\n",
        .{zero_bits},
    );

    try writer.print("end rtl;\n", .{});
}

// write binary representation of val into buf, padded to width, return slice
fn binStr(buf: []u8, val: usize, width: usize) []u8 {
    var i: usize = 0;
    while (i < width) : (i += 1) {
        const bit = (val >> @intCast(width - 1 - i)) & 1;
        buf[i] = if (bit == 1) '1' else '0';
    }
    return buf[0..width];
}

// minimum bits needed to represent n distinct values
fn bitWidth(n: usize) usize {
    if (n <= 1) return 1;
    var bits: usize = 0;
    var val: usize = n - 1;
    while (val > 0) : (val >>= 1) {
        bits += 1;
    }
    return bits;
}
