// export_vhdl.zig
// VHDL emitter for MatterScript Invocation Language networks
//
// Encoding convention (applies to every place — source, destination, internal):
//   signal[7:0] = { data[6:0], valid }
//   signal[0]   = valid bit  (1=DATA, 0=NULL)
//   signal[7:1] = 7-bit data payload (up to 127 distinct token values)
//
// A place is complete when valid='1'.
// Deasserting valid freezes a token without destroying its data value.
// Connections between networks are plain 8-bit wire assignments.

const std = @import("std");
const network = @import("network.zig");
const workspace = @import("../../common/workspace.zig");

const SIGNAL_WIDTH = 8; // data[6:0] & valid
const DATA_WIDTH   = 7; // signal[7:1]

pub fn writeVhdlNetwork(
    io: std.Io,
    allocator: std.mem.Allocator,
    namespace: []const u8,
    net: network.Network,
    output_name: []const u8,
) !void {
    // reuse workspace path helper via a minimal stub
    const output_path = try std.fmt.allocPrint(
        allocator,
        "../workspace/{s}/{s}",
        .{ namespace, output_name },
    );
    defer allocator.free(output_path);

    var file = try std.Io.Dir.cwd().createFile(io, output_path, .{});
    defer file.close(io);

    var buffer: [65536]u8 = undefined;
    var writer = file.writer(io, &buffer);

    try write(allocator, &writer.interface, net);
    try writer.interface.flush();
}

pub fn write(allocator: std.mem.Allocator, writer: anytype, net: network.Network) !void {
    for (net.definitions) |def| {
        try writeDefinition(allocator, writer, def);
        try writer.print("\n", .{});
    }
}

fn writeDefinition(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
) !void {
    try writer.print(
        \\-- generated by MatterScript IL
        \\-- definition: {s}
        \\library ieee;
        \\use ieee.std_logic_1164.all;
        \\use ieee.numeric_std.all;
        \\
        \\
    , .{def.name});

    // entity
    try writer.print("entity {s} is\n  port(\n", .{def.name});
    try writer.print("    clk : in  std_logic;\n", .{});
    try writer.print("    rst : in  std_logic;\n", .{});

    for (def.destinations) |dest| {
        try writer.print(
            "    {s} : in  std_logic_vector({d} downto 0);  -- destination place\n",
            .{ dest.name, SIGNAL_WIDTH - 1 },
        );
    }
    for (def.sources, 0..) |src, i| {
        const last = i == def.sources.len - 1;
        try writer.print(
            "    {s} : out std_logic_vector({d} downto 0){s}  -- source place\n",
            .{ src.name, SIGNAL_WIDTH - 1, if (last) "" else ";" },
        );
    }
    try writer.print("  );\nend {s};\n\n", .{def.name});

    // architecture header
    try writer.print("architecture rtl of {s} is\n", .{def.name});

    // valid signals per destination
    for (def.destinations) |dest| {
        try writer.print("  signal {s}_valid : std_logic;\n", .{dest.name});
    }
    try writer.print("  signal complete   : std_logic;\n", .{});

    // per-table signals
    for (def.constants) |tbl| {
        const tbl_id = try sanitizeName(allocator, tbl.composed_name);
        defer allocator.free(tbl_id);
        const key_bits = countDestinations(tbl.composed_name) * DATA_WIDTH;
        const val_bits = valueWidth(tbl);
        try writer.print(
            "  signal {s}_key   : std_logic_vector({d} downto 0);\n",
            .{ tbl_id, key_bits - 1 },
        );
        try writer.print(
            "  signal {s}_data  : std_logic_vector({d} downto 0);\n",
            .{ tbl_id, val_bits - 1 },
        );
        try writer.print("  signal {s}_valid : std_logic;\n", .{tbl_id});
    }

    try writer.print("begin\n\n", .{});

    // valid extraction
    try writer.print("  -- extract valid bits from destination places\n", .{});
    for (def.destinations) |dest| {
        try writer.print("  {s}_valid <= {s}(0);\n", .{ dest.name, dest.name });
    }

    // completeness
    try writer.print("\n  -- complete when all destinations are valid\n", .{});
    try writer.print("  complete <= ", .{});
    for (def.destinations, 0..) |dest, i| {
        if (i > 0) try writer.print(" and ", .{});
        try writer.print("{s}_valid", .{dest.name});
    }
    try writer.print(";\n", .{});

    // key composition
    for (def.constants) |tbl| {
        const tbl_id = try sanitizeName(allocator, tbl.composed_name);
        defer allocator.free(tbl_id);
        try writer.print("\n  -- key composition for {s}\n", .{tbl.composed_name});
        try writer.print("  {s}_key <= ", .{tbl_id});
        var i: usize = 0;
        var first = true;
        const cn = tbl.composed_name;
        while (i < cn.len) {
            if (cn[i] == '$') {
                i += 1;
                const start = i;
                while (i < cn.len and cn[i] != '$' and cn[i] != '(') i += 1;
                const dname = cn[start..i];
                if (!first) try writer.print(" & ", .{});
                try writer.print("{s}(7 downto 1)", .{dname});
                first = false;
            } else {
                i += 1;
            }
        }
        try writer.print(";\n", .{});
    }

    // ROM lookups
    for (def.constants) |tbl| {
        const tbl_id = try sanitizeName(allocator, tbl.composed_name);
        defer allocator.free(tbl_id);
        const key_bits = countDestinations(tbl.composed_name) * DATA_WIDTH;
        const val_bits = valueWidth(tbl);

        try writer.print("\n  -- ROM lookup for {s}\n", .{tbl.composed_name});
        try writer.print("  process({s}_key, complete) begin\n", .{tbl_id});
        try writer.print("    {s}_data  <= (others => '0');\n", .{tbl_id});
        try writer.print("    {s}_valid <= '0';\n", .{tbl_id});
        try writer.print("    if complete = '1' then\n", .{});
        try writer.print("      case {s}_key is\n", .{tbl_id});

        var key_buf: [128]u8 = undefined;
        var val_buf: [64]u8 = undefined;

        for (tbl.entries) |entry| {
            const key_int = std.fmt.parseInt(u64, entry.key, 10) catch 0;
            const key_str = binStr(&key_buf, key_int, key_bits);
            const val_int = std.fmt.parseInt(u64, entry.value, 10) catch 0;
            const val_str = binStr(&val_buf, val_int, val_bits);
            try writer.print(
                "        when \"{s}\" => {s}_data <= \"{s}\"; {s}_valid <= '1';\n",
                .{ key_str, tbl_id, val_str, tbl_id },
            );
        }

        try writer.print("        when others => null;\n", .{});
        try writer.print("      end case;\n    end if;\n  end process;\n", .{});
    }

    // source fills
    try writer.print("\n  -- source fills\n", .{});
    for (def.resolution) |stmt| {
        switch (stmt) {
            .fill => |f| {
                const tbl_id = try sanitizeName(allocator, f.expr);
                defer allocator.free(tbl_id);
                try writer.print(
                    "  {s} <= {s}_data & {s}_valid;\n",
                    .{ f.source_name, tbl_id, tbl_id },
                );
            },
            .invoke => |inv| {
                try writer.print(
                    "  -- TODO: component instantiation for {s}\n",
                    .{inv.name},
                );
            },
        }
    }

    try writer.print("\nend rtl;\n", .{});
}

// ----------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------

// strip $, (, ) from composed name — "$a$b()" -> "ab"
fn sanitizeName(allocator: std.mem.Allocator, composed: []const u8) ![]u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    for (composed) |c| {
        if (std.ascii.isAlphanumeric(c) or c == '_') {
            try buf.append(allocator, c);
        }
    }
    return buf.toOwnedSlice(allocator);
}

fn countDestinations(composed: []const u8) usize {
    var count: usize = 0;
    for (composed) |c| if (c == '$') { count += 1; };
    return count;
}

fn valueWidth(tbl: network.TableDef) usize {
    var max_val: u64 = 0;
    for (tbl.entries) |e| {
        const v = std.fmt.parseInt(u64, e.value, 10) catch 0;
        if (v > max_val) max_val = v;
    }
    if (max_val == 0) return 1;
    var bits: usize = 0;
    var v = max_val;
    while (v > 0) : (v >>= 1) bits += 1;
    return bits;
}

fn binStr(buf: []u8, val: u64, width: usize) []u8 {
    var i: usize = 0;
    while (i < width) : (i += 1) {
        const bit = (val >> @intCast(width - 1 - i)) & 1;
        buf[i] = if (bit == 1) '1' else '0';
    }
    return buf[0..width];
}