// top-level network and testbench wrapper emission
const std = @import("std");
const network = @import("../../network.zig");
const boundary = @import("boundary.zig");
const sanitizer = @import("../sanitizer.zig");
const sanitizeName = sanitizer.sanitizeName;
const invocation = @import("invocation.zig");

/// Emits a top-level "network" entity from Network.entry — the actual
/// invocation that ties a file's definitions together with concrete
/// argument values. A Definition-level entity alone has no fixed
/// inputs and can't be simulated directly; this is what a testbench
/// actually instantiates as its device under test.
///
/// Naming convention (matches TAG-130's checked-in testbench):
///   entity name    = "{entry.name}_network"  (e.g. "FULLADD_network")
///   unnamed output → port named "result", same convention already
///     used for an unnamed definition-level return
///   named output   → port using its own name, sanitized
///
/// Deliberately scoped: only literal-integer entry args are supported
/// (a non-literal arg gets a TODO comment and null_value rather than
/// a guess), and matched.sources/destinations are assumed to be plain
/// places — group/bundle-wrapped entry points aren't handled yet.
pub fn writeNetworkEntity(
    allocator: std.mem.Allocator,
    writer: anytype,
    net: network.Network,
) !void {
    var used_names: std.ArrayListUnmanaged([]const u8) = .empty;
    for (net.entries) |entry| {
        try writeOneNetworkEntity(allocator, writer, net, entry, &used_names);
    }
}

pub fn writeOneNetworkEntity(
    allocator: std.mem.Allocator,
    writer: anytype,
    net: network.Network,
    entry: network.EntryInvocation,
    used_names: *std.ArrayListUnmanaged([]const u8),
) !void {
    const matched = for (net.definitions) |d| {
        if (std.ascii.eqlIgnoreCase(d.name, entry.name)) break d;
    } else return;

    const entry_name_id = try sanitizeName(allocator, entry.name);
    defer allocator.free(entry_name_id);
    const base_id = try std.fmt.allocPrint(allocator, "{s}_network", .{entry_name_id});
    defer allocator.free(base_id);
    // Multiple entries can invoke the same definition (e.g. several
    // fanin(...) calls with different literal inputs) — uniquify so
    // GHDL never sees the same entity declared twice in one file.
    const entity_id = try sanitizer.uniqueVhdlName(allocator, used_names.items, base_id);
    try used_names.append(allocator, try allocator.dupe(u8, entity_id));

    var output_names: std.ArrayListUnmanaged([]const u8) = .empty;
    for (entry.destinations) |output| {
        const raw_name = switch (output.kind) {
            .place => output.name,
            else => output.text,
        };
        const candidate = if (raw_name.len == 0) "result" else raw_name;
        // Two unnamed destination slots (e.g. TAG-129's own
        // "(< > CARRYOUT < >)") would otherwise both fall back to the
        // literal "result", producing two identical port declarations.
        const unique = try sanitizer.uniqueVhdlName(allocator, output_names.items, candidate);
        try output_names.append(allocator, unique);
    }
    // The entry invocation can name fewer destinations than the DUT
    // actually has (fanout's 5 outputs vs. an entry that only cares
    // about one, say). writeNetworkDestMapping below falls back to a
    // placeholder for every DUT output beyond what output_names
    // covers — that placeholder must actually be declared as a port
    // here, or ghdl reports "no declaration for result" on the
    // resulting port-map reference.
    const dut_output_count = boundary.boundaryCount(matched.destinations);
    while (output_names.items.len < dut_output_count) {
        const unique = try sanitizer.uniqueVhdlName(allocator, output_names.items, "result");
        try output_names.append(allocator, unique);
    }

    try writer.print(
        \\-- generated by MatterScript IPL
        \\-- top-level network entity for entry invocation: {s}
        \\library ieee;
        \\use ieee.std_logic_1164.all;
        \\use ieee.numeric_std.all;
        \\use work.matterscript_ncl.all;
        \\
        \\
    , .{entry.name});

    if (output_names.items.len == 0) {
        // No outputs — VHDL doesn't allow an empty port list, so omit
        // the port clause entirely rather than emit port();
        try writer.print("entity {s} is\nend {s};\n\n", .{ entity_id, entity_id });
    } else {
        try writer.print("entity {s} is\n  port(\n", .{entity_id});
        for (output_names.items, 0..) |name, i| {
            const id = try sanitizeName(allocator, name);
            defer allocator.free(id);
            const last = i == output_names.items.len - 1;
            try writer.print("    {s} : out ncl_signal{s}\n", .{ id, if (last) "" else ";" });
        }
        try writer.print("  );\nend {s};\n\n", .{entity_id});
    }

    try writer.print("architecture rtl of {s} is\n", .{entity_id});
    // Same padding issue as output_names above, mirrored on the
    // source side: writeNetworkSourceMapping walks matched.sources
    // (the DUT's real, flattened input count) and increments a
    // shared arg_index for each one, so if the entry invocation
    // supplied fewer literal arguments than the DUT actually has
    // inputs, references to the missing arg_N signals would never
    // have been declared here at all.
    const dut_source_count = boundary. boundaryCount(matched.sources);
    const declared_source_count = @max(entry.sources.len, dut_source_count);
    for (0..declared_source_count) |i| {
        try writer.print("  signal arg_{d} : ncl_signal;\n", .{i});
    }
    try writer.print("begin\n\n", .{});

    for (entry.sources, 0..) |arg, i| {
        const text = invocation.argToText(arg);
        const trimmed = std.mem.trim(u8, text, " \t\r\n");
        const value = std.fmt.parseInt(u64, trimmed, 10) catch {
            try writer.print("  -- TODO: non-literal entry argument '{s}' not yet supported\n", .{trimmed});
            try writer.print("  arg_{d} <= null_value;\n", .{i});
            continue;
        };
        try writer.print("  arg_{d} <= data_value({d});\n", .{ i, value });
    }
    // Any DUT inputs beyond what the entry invocation supplied still
    // need a defined value — tie them to null_value rather than leave
    // them floating.
    if (dut_source_count > entry.sources.len) {
        try writer.print("  -- entry invocation supplied fewer arguments than the DUT has inputs\n", .{});
        for (entry.sources.len..dut_source_count) |i| {
            try writer.print("  arg_{d} <= null_value;\n", .{i});
        }
    }

    const def_id = try invocation.scopedDefinitionName(allocator, "", matched.name);
    defer allocator.free(def_id);
    try writer.print("\n  dut : entity work.{s} port map (\n", .{def_id});

    var arg_index: usize = 0;
    var first_port = true;
    for (matched.sources) |src| {
        try writeNetworkSourceMapping(allocator, writer, src, &arg_index, entry, &first_port);
    }

    var output_index: usize = 0;
    for (matched.destinations) |dst| {
        try writeNetworkDestMapping(allocator, writer, dst, &output_index, output_names.items, &first_port);
    }
    try writer.print("\n  );\n", .{});
    try writer.print("\nend rtl;\n", .{});
}

fn writeNetworkSourceMapping(
    allocator: std.mem.Allocator,
    writer: anytype,
    arg: network.Arg,
    arg_index: *usize,
    entry: network.EntryInvocation,
    first_port: *bool,
) !void {
    switch (arg.kind) {
        .group => if (arg.group) |grp| {
            for (grp.places) |child| {
                try writeNetworkSourceMapping(allocator, writer, child, arg_index, entry, first_port);
            }
        },
        .place => {
            const port_id = try sanitizeName(allocator, arg.name);
            defer allocator.free(port_id);
            
            if (first_port.*) {
                try writer.print("\n    {s} => arg_{d}", .{ port_id, arg_index.* });
                first_port.* = false;
            } else {
                try writer.print(",\n    {s} => arg_{d}", .{ port_id, arg_index.* });
            }
            arg_index.* += 1;
        },
        else => {},
    }
}

fn writeNetworkDestMapping(
    allocator: std.mem.Allocator,
    writer: anytype,
    arg: network.Arg,
    output_index: *usize,
    output_names: []const []const u8,
    first_port: *bool,
) !void {
    switch (arg.kind) {
        .group => if (arg.group) |grp| {
            for (grp.places) |child| {
                try writeNetworkDestMapping(allocator, writer, child, output_index, output_names, first_port);
            }
        },
        .place => {
            const port_id = try sanitizeName(allocator, arg.name);
            defer allocator.free(port_id);
            const output_name = if (output_index.* < output_names.len) output_names[output_index.*] else "result";
            const output_id = try sanitizeName(allocator, output_name);
            defer allocator.free(output_id);

            if (first_port.*) {
                try writer.print("\n    {s} => {s}", .{ port_id, output_id });
                first_port.* = false;
            } else {
                try writer.print(",\n    {s} => {s}", .{ port_id, output_id });
            }
            output_index.* += 1;
        },
        else => {},
    }
}
