// Responsibility: Emits VHDL entity interfaces, architecture rtl bodies,
// component declarations, port mappings, and handles intermediate signal
// generation and boundary checks.

const std = @import("std");
const network = @import("../network.zig");
const sanitizer = @import("sanitizer.zig");
const sanitizeName = sanitizer.sanitizeName;
const constants = @import("constants.zig");
const lookup = @import("lookup.zig");

const DATA_WIDTH = constants.DATA_WIDTH;

fn argContainsName(arg: network.Arg, name: []const u8) bool {
    switch (arg.kind) {
        .group => if (arg.group) |grp| {
            for (grp.places) |child| {
                if (argContainsName(child, name)) return true;
            }
        },
        .place => return std.mem.eql(u8, arg.name, name),
        else => {},
    }
    return false;
}

/// Emits a VHDL entity and architecture body for a single MatterScript definition,
/// normalizing destination defaults and identifiers, and recursively processing any
/// nested child definitions.
pub fn writeDefinition(
    allocator: std.mem.Allocator,
    writer: anytype,
    raw_def: network.Definition,
    scope: []const u8,
) !void {
    // §12.3.4 "Single Return to Place of Invocation" — if this
    // definition has no destination list at all, its resolution's
    // top-level fill(s) express the implicit return(s) instead,
    // whether unnamed (synthesize "result") or already named (e.g.
    // "out1" in "A[out1< $in >]"). Normalized ONCE here, into a
    // corrected copy of `def`, so every downstream use — component
    // declarations, intermediate signals, lookup tables, fill
    // emission — sees consistent data, instead of patching each call
    // site individually and risking missing one.
    var def = raw_def;
    if (def.destinations.len == 0) {
        var names: std.ArrayListUnmanaged([]const u8) = .empty;
        var normalized: std.ArrayListUnmanaged(network.Statement) = .empty;
        for (def.resolution) |stmt| {
            switch (stmt) {
                .fill => |raw_f| {
                    var f = raw_f;
                    if (f.dest_name.len == 0) f.dest_name = "result";
                    var have = false;
                    for (names.items) |n| {
                        if (std.mem.eql(u8, n, f.dest_name)) {
                            have = true;
                            break;
                        }
                    }
                    if (!have) try names.append(allocator, f.dest_name);
                    try normalized.append(allocator, .{ .fill = f });
                },
                else => try normalized.append(allocator, stmt),
            }
        }
        if (names.items.len > 0) {
            var dests: std.ArrayListUnmanaged(network.Arg) = .empty;
            for (names.items) |n| try dests.append(allocator, .{ .kind = .place, .name = n });
            def.destinations = try dests.toOwnedSlice(allocator);
            def.resolution = try normalized.toOwnedSlice(allocator);
        }
    }

    // IPL names are case-sensitive, whereas VHDL identifiers are not.  Give
    // every exact IPL spelling a stable, lowercase VHDL spelling before any
    // declaration or reference is emitted.  This is deliberately done to the
    // whole definition, rather than only to ports: `a` and `A` must remain
    // distinct in assignments, expression references, and intermediate
    // signals as well as in the entity interface.
    def = try sanitizer.normalizeDefinitionIdentifiers(allocator, def);

    {
        const def_id = try scopedDefinitionName(allocator, scope, def.name);
        defer allocator.free(def_id);
        try writer.print(
            \\-- generated by MatterScript IPL
            \\-- definition: {s}
            \\library ieee;
            \\use ieee.std_logic_1164.all;
            \\use ieee.numeric_std.all;
            \\use work.matterscript_ncl.all;
            \\
            \\
        , .{def.name});

        // entity
        try writer.print("entity {s} is\n  port(\n", .{def_id});
        try writer.print("    clk : in  std_logic;\n", .{});
        const boundary_count = boundaryCount(def.sources) + boundaryCount(def.destinations);
        try writer.print("    rst : in  std_logic{s}\n", .{if (boundary_count == 0) "" else ";"});

        // sources → inputs (tokens flow IN to the definition)
        var port_index: usize = 0;
        var port_names: std.ArrayListUnmanaged([]const u8) = .empty;
        for (def.sources) |src| {
            try writeBoundaryPorts(allocator, writer, src, "in", &port_index, boundary_count, &port_names);
        }

        // destinations → outputs (tokens flow OUT of the definition)
        for (def.destinations) |dest| {
            try writeBoundaryPorts(allocator, writer, dest, "out", &port_index, boundary_count, &port_names);
        }
        try writer.print("  );\nend {s};\n\n", .{def_id});
        // architecture
        try writer.print("architecture rtl of {s} is\n", .{def_id});

        // valid signals — one per source (input)
        for (def.sources) |src| {
            try writeBoundaryValidDeclarations(allocator, writer, src);
        }
        try writer.print("  signal complete   : std_logic;\n", .{});

        // per-table signals
        for (def.constants) |tbl| {
            const tbl_id = try sanitizeName(allocator, tbl.composed_name);
            defer allocator.free(tbl_id);
            const key_bits = lookup.countSources(tbl.composed_name) * DATA_WIDTH;
            const val_bits = try lookup.tableValueWidth(allocator, tbl);
            try writer.print("  signal {s}_key   : std_logic_vector({d} downto 0);\n", .{ tbl_id, key_bits - 1 });
            try writer.print("  signal {s}_data  : std_logic_vector({d} downto 0);\n", .{ tbl_id, val_bits - 1 });
            try writer.print("  signal {s}_valid : std_logic;\n", .{tbl_id});
        }

        var intermediate_names: std.ArrayListUnmanaged([]const u8) = .empty;
        for (def.resolution) |stmt| {
            switch (stmt) {
                .fill => |fill| {
                    // A fill's destination (e.g. "p0" in "p0<point(...)>")
                    // is only a boundary port when it's actually
                    // declared in sources/destinations — otherwise it's
                    // a purely internal place that still needs a
                    // signal declared for it, or ghdl reports "no
                    // declaration for <name>" on the assignment below.
                    // Any $-referenced names inside the expression
                    // itself need the same treatment (mirroring the
                    // .invoke and .pure_value cases here).
                    try writeIntermediateSignal(allocator, writer, def, &intermediate_names, fill.dest_name);
                    try writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, fill.expr);
                },
                .invoke => |inv| {
                    for (inv.destinations) |dest| {
                        try writeIntermediatePlaceSignal(allocator, writer, def, &intermediate_names, dest);
                    }
                    for (inv.sources) |src| {
                        try writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, argToText(src));
                    }
                },
                .pure_value => |value| try writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, value),
                .directive => |d| {
                    try writer.print("  -- @{s}({s}) (directive not yet interpreted)\n", .{ d.name, d.args });
                },
            }
        }

        var component_names: std.ArrayListUnmanaged([]const u8) = .empty;
        for (def.resolution) |stmt| {
            if (stmt != .invoke) continue;
            const inv = stmt.invoke;
            var already_declared = false;
            for (component_names.items) |name| {
                if (std.ascii.eqlIgnoreCase(name, inv.name)) {
                    already_declared = true;
                    break;
                }
            }
            if (already_declared) continue;
            const name = try allocator.dupe(u8, inv.name);
            try component_names.append(allocator, name);
            const component_id = try invocationDefinitionName(allocator, def, scope, inv.name);
            defer allocator.free(component_id);
            try writeComponentDeclaration(writer, inv, component_id);
        }

        for (def.resolution, 0..) |stmt, invocation_index| {
            if (stmt != .invoke) continue;
            const inv = stmt.invoke;
            for (inv.sources, 0..) |_, argument_index| {
                try writer.print("  signal invocation_{d}_arg_{d} : ncl_signal;\n", .{ invocation_index, argument_index });
            }
            for (inv.destinations, 0..) |output, output_index| {
                if (output.group == null and output.name.len != 0) continue;
                try writer.print("  signal invocation_{d}_output_{d} : ncl_signal;\n", .{ invocation_index, output_index });
            }
        }
        try writer.print("begin\n\n", .{});

        for (def.resolution, 0..) |stmt, invocation_index| {
            if (stmt != .invoke) continue;
            const inv = stmt.invoke;
            for (inv.sources, 0..) |arg, argument_index| {
                try writeInvocationArgument(allocator, writer, invocation_index, argument_index, arg);
            }
            for (inv.destinations, 0..) |output, output_index| {
                if (output.group == null and output.name.len != 0) continue;
                try writer.print("  invocation_{d}_output_{d} <= null_value;\n", .{ invocation_index, output_index });
            }
            try writeInvocationInstance(allocator, writer, def, scope, inv, invocation_index);
        }

        // valid extraction from source places (inputs)
        try writer.print("  -- extract valid bits from source places (inputs)\n", .{});
        for (def.sources) |src| {
            try writeBoundaryValidAssignments(allocator, writer, src);
        }

        // completeness: AND of all source valids
        try writer.print("\n  -- complete when all source places are valid\n", .{});

        var valid_exprs: std.ArrayListUnmanaged([]const u8) = .empty;
        defer {
            for (valid_exprs.items) |expr| allocator.free(expr);
            valid_exprs.deinit(allocator);
        }

        for (def.sources) |src| {
            var aw: std.Io.Writer.Allocating = .init(allocator);
            defer aw.deinit();

            try writeBoundaryValidExpression(allocator, &aw.writer, src);

            const trimmed = std.mem.trim(u8, aw.written(), " \t\r\n");
            if (trimmed.len > 0) {
                try valid_exprs.append(allocator, try allocator.dupe(u8, trimmed));
            }
        }

        if (valid_exprs.items.len == 0) {
            try writer.print("  complete <= '1';\n", .{});
        } else {
            try writer.print("  complete <= ", .{});
            for (valid_exprs.items, 0..) |expr, i| {
                if (i > 0) try writer.print(" and ", .{});
                try writer.print("{s}", .{expr});
            }
            try writer.print(";\n", .{});
        }

        // key composition
        for (def.constants) |tbl| {
            const tbl_id = try sanitizeName(allocator, tbl.composed_name);
            defer allocator.free(tbl_id);
            try writer.print("\n  -- key composition for {s}\n", .{tbl.composed_name});
            try writer.print("  {s}_key <= ", .{tbl_id});
            var i: usize = 0;
            var first = true;
            const cn = tbl.composed_name;
            while (i < cn.len) {
                if (cn[i] == '$') {
                    i += 1;
                    const start = i;
                    while (i < cn.len and cn[i] != '$' and cn[i] != '(') i += 1;
                    const sname = cn[start..i];
                    if (!first) try writer.print(" & ", .{});
                    try writer.print("{s}(7 downto 1)", .{sname});
                    first = false;
                } else i += 1;
            }
            try writer.print(";\n", .{});
        }

        // ROM lookups
        for (def.constants) |tbl| {
            const tbl_id = try sanitizeName(allocator, tbl.composed_name);
            defer allocator.free(tbl_id);
            const val_bits = try lookup.tableValueWidth(allocator, tbl);

            try writer.print("\n  -- ROM lookup for {s}\n", .{tbl.composed_name});
            try writer.print("  process({s}_key, complete) begin\n", .{tbl_id});
            try writer.print("    {s}_data  <= (others => '0');\n", .{tbl_id});
            try writer.print("    {s}_valid <= '0';\n", .{tbl_id});
            try writer.print("    if complete = '1' then\n", .{});
            try writer.print("      case {s}_key is\n", .{tbl_id});

            switch (tbl.kind) {
                .explicit => |entries| {
                    var key_buf: [128]u8 = undefined;
                    var val_buf: [64]u8 = undefined;
                    for (entries) |entry| {
                        var key_pos: usize = 0;
                        for (entry.key) |ch| {
                            const dv: u64 = ch - '0';
                            const seg = lookup.binStr(key_buf[key_pos..], dv, DATA_WIDTH);
                            key_pos += seg.len;
                        }
                        const key_str = key_buf[0..key_pos];
                        const val_int = std.fmt.parseInt(u64, entry.value, 10) catch 0;
                        const val_str = lookup.binStr(&val_buf, val_int, val_bits);
                        try writer.print("        when \"{s}\" => {s}_data <= \"{s}\"; {s}_valid <= '1';\n", .{ key_str, tbl_id, val_str, tbl_id });
                    }
                },
                .generate => {
                    // TODO
                },
            }

            try writer.print("        when others => null;\n", .{});
            try writer.print("      end case;\n    end if;\n  end process;\n", .{});
        }

        // destination fills (outputs)
        try writer.print("\n  -- destination fills (outputs)\n", .{});
        if (!try lookup.writeContainedLookupTable(allocator, writer, def)) {
            for (def.resolution) |stmt| {
                switch (stmt) {
                    .fill => |f| {
                        const literal = std.fmt.parseInt(u64, std.mem.trim(u8, f.expr, " \t\r\n"), 10) catch null;
                        if (literal) |value| {
                            const dest_id = try sanitizeName(allocator, f.dest_name);
                            defer allocator.free(dest_id);
                            try writer.print("  {s} <= data_value({d});\n", .{ dest_id, value });
                        } else if (!try writeExpressionFill(allocator, writer, f)) {
                            const dest_id = try sanitizeName(allocator, f.dest_name);
                            defer allocator.free(dest_id);
                            try writer.print("  {s} <= null_value;\n", .{dest_id});
                        }
                    },
                    .invoke => |inv| {
                        _ = inv;
                    },
                    .pure_value => |v| {
                        try writer.print("  -- TODO: pure value expression {s} (not a recognized lookup-table shape)\n", .{v});
                    },
                    .directive => |d| {
                        try writer.print("  -- @{s}({s}) (directive not yet interpreted)\n", .{ d.name, d.args });
                    },
                }
            }
        }

        try writer.print("\nend rtl;\n", .{});

        for (def.contained) |contained| {
            // Guard empty string before checking if first character is a digit
            if (contained.name.len == 0 or std.ascii.isDigit(contained.name[0])) continue;
            try writer.print("\n", .{});
            try writeDefinition(allocator, writer, contained, def_id);
        }
    }
}

/// Emits a top-level "network" entity from Network.entry — the actual
/// invocation that ties a file's definitions together with concrete
/// argument values. A Definition-level entity alone has no fixed
/// inputs and can't be simulated directly; this is what a testbench
/// actually instantiates as its device under test.
///
/// Naming convention (matches TAG-130's checked-in testbench):
///   entity name    = "{entry.name}_network"  (e.g. "FULLADD_network")
///   unnamed output → port named "result", same convention already
///     used for an unnamed definition-level return
///   named output   → port using its own name, sanitized
///
/// Deliberately scoped: only literal-integer entry args are supported
/// (a non-literal arg gets a TODO comment and null_value rather than
/// a guess), and matched.sources/destinations are assumed to be plain
/// places — group/bundle-wrapped entry points aren't handled yet.
pub fn writeNetworkEntity(
    allocator: std.mem.Allocator,
    writer: anytype,
    net: network.Network,
) !void {
    var used_names: std.ArrayListUnmanaged([]const u8) = .empty;
    for (net.entries) |entry| {
        try writeOneNetworkEntity(allocator, writer, net, entry, &used_names);
    }
}

fn writeOneNetworkEntity(
    allocator: std.mem.Allocator,
    writer: anytype,
    net: network.Network,
    entry: network.EntryInvocation,
    used_names: *std.ArrayListUnmanaged([]const u8),
) !void {
    const matched = for (net.definitions) |d| {
        if (std.ascii.eqlIgnoreCase(d.name, entry.name)) break d;
    } else return;

    const entry_name_id = try sanitizeName(allocator, entry.name);
    defer allocator.free(entry_name_id);
    const base_id = try std.fmt.allocPrint(allocator, "{s}_network", .{entry_name_id});
    defer allocator.free(base_id);
    // Multiple entries can invoke the same definition (e.g. several
    // fanin(...) calls with different literal inputs) — uniquify so
    // GHDL never sees the same entity declared twice in one file.
    const entity_id = try sanitizer.uniqueVhdlName(allocator, used_names.items, base_id);
    try used_names.append(allocator, try allocator.dupe(u8, entity_id));

    var output_names: std.ArrayListUnmanaged([]const u8) = .empty;
    for (entry.destinations) |output| {
        const raw_name = switch (output.kind) {
            .place => output.name,
            else => output.text,
        };
        const candidate = if (raw_name.len == 0) "result" else raw_name;
        // Two unnamed destination slots (e.g. TAG-129's own
        // "(< > CARRYOUT < >)") would otherwise both fall back to the
        // literal "result", producing two identical port declarations.
        const unique = try sanitizer.uniqueVhdlName(allocator, output_names.items, candidate);
        try output_names.append(allocator, unique);
    }
    // The entry invocation can name fewer destinations than the DUT
    // actually has (fanout's 5 outputs vs. an entry that only cares
    // about one, say). writeNetworkDestMapping below falls back to a
    // placeholder for every DUT output beyond what output_names
    // covers — that placeholder must actually be declared as a port
    // here, or ghdl reports "no declaration for result" on the
    // resulting port-map reference.
    const dut_output_count = boundaryCount(matched.destinations);
    while (output_names.items.len < dut_output_count) {
        const unique = try sanitizer.uniqueVhdlName(allocator, output_names.items, "result");
        try output_names.append(allocator, unique);
    }

    try writer.print(
        \\-- generated by MatterScript IPL
        \\-- top-level network entity for entry invocation: {s}
        \\library ieee;
        \\use ieee.std_logic_1164.all;
        \\use ieee.numeric_std.all;
        \\use work.matterscript_ncl.all;
        \\
        \\
    , .{entry.name});

    if (output_names.items.len == 0) {
        // No outputs — VHDL doesn't allow an empty port list, so omit
        // the port clause entirely rather than emit port();
        try writer.print("entity {s} is\nend {s};\n\n", .{ entity_id, entity_id });
    } else {
        try writer.print("entity {s} is\n  port(\n", .{entity_id});
        for (output_names.items, 0..) |name, i| {
            const id = try sanitizeName(allocator, name);
            defer allocator.free(id);
            const last = i == output_names.items.len - 1;
            try writer.print("    {s} : out ncl_signal{s}\n", .{ id, if (last) "" else ";" });
        }
        try writer.print("  );\nend {s};\n\n", .{entity_id});
    }

    try writer.print("architecture rtl of {s} is\n", .{entity_id});
    // Same padding issue as output_names above, mirrored on the
    // source side: writeNetworkSourceMapping walks matched.sources
    // (the DUT's real, flattened input count) and increments a
    // shared arg_index for each one, so if the entry invocation
    // supplied fewer literal arguments than the DUT actually has
    // inputs, references to the missing arg_N signals would never
    // have been declared here at all.
    const dut_source_count = boundaryCount(matched.sources);
    const declared_source_count = @max(entry.sources.len, dut_source_count);
    for (0..declared_source_count) |i| {
        try writer.print("  signal arg_{d} : ncl_signal;\n", .{i});
    }
    try writer.print("begin\n\n", .{});

    for (entry.sources, 0..) |arg, i| {
        const text = argToText(arg);
        const trimmed = std.mem.trim(u8, text, " \t\r\n");
        const value = std.fmt.parseInt(u64, trimmed, 10) catch {
            try writer.print("  -- TODO: non-literal entry argument '{s}' not yet supported\n", .{trimmed});
            try writer.print("  arg_{d} <= null_value;\n", .{i});
            continue;
        };
        try writer.print("  arg_{d} <= data_value({d});\n", .{ i, value });
    }
    // Any DUT inputs beyond what the entry invocation supplied still
    // need a defined value — tie them to null_value rather than leave
    // them floating.
    if (dut_source_count > entry.sources.len) {
        try writer.print("  -- entry invocation supplied fewer arguments than the DUT has inputs\n", .{});
        for (entry.sources.len..dut_source_count) |i| {
            try writer.print("  arg_{d} <= null_value;\n", .{i});
        }
    }

    const def_id = try scopedDefinitionName(allocator, "", matched.name);
    defer allocator.free(def_id);
    try writer.print("\n  dut : entity work.{s} port map (\n", .{def_id});
    try writer.print("    clk => '0', rst => '0'", .{});

    var arg_index: usize = 0;
    for (matched.sources) |src| {
        try writeNetworkSourceMapping(allocator, writer, src, &arg_index, entry);
    }

    var output_index: usize = 0;
    for (matched.destinations) |dst| {
        try writeNetworkDestMapping(allocator, writer, dst, &output_index, output_names.items);
    }
    try writer.print("\n  );\n", .{});
    try writer.print("\nend rtl;\n", .{});
}

fn writeNetworkSourceMapping(
    allocator: std.mem.Allocator,
    writer: anytype,
    arg: network.Arg,
    arg_index: *usize,
    entry: network.EntryInvocation,
) !void {
    switch (arg.kind) {
        .group => if (arg.group) |grp| {
            for (grp.places) |child| {
                try writeNetworkSourceMapping(allocator, writer, child, arg_index, entry);
            }
        },
        .place => {
            const port_id = try sanitizeName(allocator, arg.name);
            defer allocator.free(port_id);
            try writer.print(",\n    {s} => arg_{d}", .{ port_id, arg_index.* });
            arg_index.* += 1;
        },
        else => {},
    }
}

fn writeNetworkDestMapping(
    allocator: std.mem.Allocator,
    writer: anytype,
    arg: network.Arg,
    output_index: *usize,
    output_names: []const []const u8,
) !void {
    switch (arg.kind) {
        .group => if (arg.group) |grp| {
            for (grp.places) |child| {
                try writeNetworkDestMapping(allocator, writer, child, output_index, output_names);
            }
        },
        .place => {
            const port_id = try sanitizeName(allocator, arg.name);
            defer allocator.free(port_id);
            const output_name = if (output_index.* < output_names.len) output_names[output_index.*] else "result";
            const output_id = try sanitizeName(allocator, output_name);
            defer allocator.free(output_id);

            try writer.print(",\n    {s} => {s}", .{ port_id, output_id });
            output_index.* += 1;
        },
        else => {},
    }
}

fn writeComponentDeclaration(
    writer: anytype,
    inv: network.Invocation,
    component_id: []const u8,
) !void {
    try writer.print("  component {s}\n    port(\n", .{component_id});
    try writer.print("      clk : in std_logic;\n      rst : in std_logic", .{});
    const port_count = inv.sources.len + inv.destinations.len;
    if (port_count > 0) try writer.print(";", .{});
    try writer.print("\n", .{});

    for (inv.sources, 0..) |_, i| {
        try writer.print("      arg_{d} : in ncl_signal{s}\n", .{ i, if (i + 1 == port_count) "" else ";" });
    }
    for (inv.destinations, 0..) |_, i| {
        try writer.print("      output_{d} : out ncl_signal{s}\n", .{ i, if (i + inv.sources.len + 1 == port_count) "" else ";" });
    }
    try writer.print("    );\n  end component;\n\n", .{});
}

fn writeInvocationArgument(
    allocator: std.mem.Allocator,
    writer: anytype,
    invocation_index: usize,
    argument_index: usize,
    argument: network.Arg,
) !void {
    const signal_name = try std.fmt.allocPrint(allocator, "invocation_{d}_arg_{d}", .{ invocation_index, argument_index });
    defer allocator.free(signal_name);

    const text = argToText(argument);
    const trimmed = std.mem.trim(u8, text, " \t\r\n");

    if (argument.kind == .group) {
        if (argument.group) |group| {
            if (group.kind == .arbitration) {
                try writer.print("  -- Arbiter input competition group\n", .{});
            }
        }
        try writer.print("  {s} <= null_value;\n", .{signal_name});
    } else if (trimmed.len > 1 and trimmed[0] == '$' and std.mem.indexOfScalar(u8, trimmed[1..], '$') == null) {
        const source_id = try sanitizeName(allocator, trimmed[1..]);
        defer allocator.free(source_id);
        try writer.print("  {s} <= {s};\n", .{ signal_name, source_id });
    } else if (std.fmt.parseInt(u64, trimmed, 10)) |value| {
        try writer.print("  {s} <= data_value({d});\n", .{ signal_name, value });
    } else |_| {
        try writer.print("  {s} <= null_value;\n", .{signal_name});
    }
}

fn writeInvocationInstance(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
    scope: []const u8,
    inv: network.Invocation,
    invocation_index: usize,
) !void {
    const component_id = try invocationDefinitionName(allocator, def, scope, inv.name);
    defer allocator.free(component_id);
    try writer.print("  invocation_{d} : {s} port map (clk => clk, rst => rst", .{ invocation_index, component_id });
    for (inv.sources, 0..) |_, argument_index| {
        try writer.print(", arg_{d} => invocation_{d}_arg_{d}", .{ argument_index, invocation_index, argument_index });
    }
    for (inv.destinations, 0..) |output, output_index| {
        if (output.group != null or output.name.len == 0) {
            try writer.print(", output_{d} => invocation_{d}_output_{d}", .{ output_index, invocation_index, output_index });
        } else {
            const output_id = try placeName(allocator, output);
            defer allocator.free(output_id);
            try writer.print(", output_{d} => {s}", .{ output_index, output_id });
        }
    }
    try writer.print(");\n", .{});
}

// Boundary Helpers

/// Recursively counts the total number of individual scalar or port places 
/// contained within a slice of definition arguments or groups.
fn boundaryCount(args: []const network.Arg) usize {
    // Deliberately mirrors writeBoundaryPorts' own switch exactly
    // (group → recurse, place → +1, anything else → +0), rather than
    // counting every non-group kind, so this can never again disagree
    // with what actually gets printed — see the parseArg fix for
    // '$name' destinations for what happens when it does.
    var count: usize = 0;
    for (args) |arg| {
        switch (arg.kind) {
            .group => if (arg.group) |grp| {
                count += boundaryCount(grp.places);
            },
            .place => count += 1,
            else => {},
        }
    }
    return count;
}

fn placeBoundaryCount(place: network.Place) usize {
    const group = place.group orelse return 1;
    if (group.kind == .bundle) return 1;
    return boundaryCount(group.places);
}

/// Recursively generates VHDL port definitions (`in` or `out`) for boundary sources 
/// and destinations, mapping them to `ncl_signal` types.
fn writeBoundaryPorts(
    allocator: std.mem.Allocator,
    writer: anytype,
    arg: network.Arg,
    dir: []const u8,
    port_index: *usize,
    boundary_count: usize,
    port_names: *std.ArrayListUnmanaged([]const u8),
) !void {
    switch (arg.kind) {
        .group => if (arg.group) |grp| {
            for (grp.places) |child| {
                try writeBoundaryPorts(allocator, writer, child, dir, port_index, boundary_count, port_names);
            }
        },
        .place => {
            const port_id = try sanitizeName(allocator, arg.name);
            defer allocator.free(port_id);
            try port_names.append(allocator, try allocator.dupe(u8, port_id));

            port_index.* += 1;
            const is_last = (port_index.* == boundary_count);
            // ncl_signal (SIGNAL_WIDTH = DATA_WIDTH + 1 bits), not a
            // bare DATA_WIDTH-bit vector: every consumer downstream
            // (is_data/payload/null_value/data_value, and the
            // "x(7 downto 1)" case-key builders) already assumes the
            // 8-bit encoding with an embedded validity bit at index 0.
            // Declaring the port itself one bit narrower is what made
            // valid_of(x) unresolvable and produced the "value
            // constraints don't match target ones" / "left bound
            // incompatible with range" warnings on every assignment.
            try writer.print("    {s} : {s} ncl_signal{s}\n", .{
                port_id,
                dir,
                if (is_last) "" else ";",
            });
        },
        else => {},
    }
}

fn writeBoundaryValidDeclarations(
    allocator: std.mem.Allocator,
    writer: anytype,
    arg: network.Arg,
) !void {
    switch (arg.kind) {
        .group => if (arg.group) |grp| {
            for (grp.places) |child| {
                try writeBoundaryValidDeclarations(allocator, writer, child);
            }
        },
        .place => {
            const port_id = try sanitizeName(allocator, arg.name);
            defer allocator.free(port_id);
            try writer.print("  signal {s}_valid : std_logic;\n", .{port_id});
        },
        else => {},
    }
}

fn writeBoundaryValidAssignments(
    allocator: std.mem.Allocator,
    writer: anytype,
    arg: network.Arg,
) !void {
    switch (arg.kind) {
        .group => if (arg.group) |grp| {
            for (grp.places) |child| {
                try writeBoundaryValidAssignments(allocator, writer, child);
            }
        },
        .place => {
            const port_id = try sanitizeName(allocator, arg.name);
            defer allocator.free(port_id);
            try writer.print("  {s}_valid <= valid_of({s});\n", .{ port_id, port_id });
        },
        else => {},
    }
}

fn writeBoundaryValidExpression(
    allocator: std.mem.Allocator,
    writer: anytype,
    arg: network.Arg,
) !void {
    switch (arg.kind) {
        .group => if (arg.group) |grp| {
            for (grp.places, 0..) |child, i| {
                if (i > 0) try writer.print(" and ", .{});
                try writeBoundaryValidExpression(allocator, writer, child);
            }
        },
        .place => {
            const port_id = try sanitizeName(allocator, arg.name);
            defer allocator.free(port_id);
            try writer.print("{s}_valid", .{port_id});
        },
        else => {},
    }
}

/// Unwraps a network argument into its raw text representation, handling places,
/// literals, expressions, and group kinds.
fn argToText(arg: network.Arg) []const u8 {
    return switch (arg.kind) {
        .place => if (arg.name.len > 0) arg.name else arg.text,
        .literal, .expression => arg.text,
        .group => if (arg.group) |g| switch (g.kind) {
            .bundle => "[group]",
            .mutex => "{mutex}",
            .arbitration => "{{arbitration}}",
        } else "",
    };
}

/// Attempts to evaluate and emit an expression fill (such as direct signal mapping 
/// or equality checks against constants), returning `true` if successfully handled.
fn writeExpressionFill(
    allocator: std.mem.Allocator,
    writer: anytype,
    fill: network.SourceFill,
) !bool {
    const expression = std.mem.trim(u8, fill.expr, " \t\r\n");
    const dest_id = try sanitizeName(allocator, fill.dest_name);
    defer allocator.free(dest_id);

    if (expression.len > 1 and expression[0] == '$') {
        var end = expression.len;
        if (std.mem.indexOfScalar(u8, expression, '(')) |open| end = open;
        const source_id = try sanitizeName(allocator, expression[1..end]);
        defer allocator.free(source_id);
        try writer.print("  {s} <= {s};\n", .{ dest_id, source_id });
        return true;
    }

    if (std.mem.startsWith(u8, expression, "Equal(")) {
        const dollar = std.mem.indexOfScalar(u8, expression, '$') orelse return false;
        const comma = std.mem.indexOfScalarPos(u8, expression, dollar, ',') orelse return false;
        const source_id = try sanitizeName(allocator, expression[dollar + 1 .. comma]);
        defer allocator.free(source_id);
        const value_end = std.mem.indexOfScalarPos(u8, expression, comma + 1, ')') orelse return false;
        const value_text = std.mem.trim(u8, expression[comma + 1 .. value_end], " \t\r\n");
        const value = std.fmt.parseInt(u64, value_text, 10) catch return false;
        try writer.print("  process({s}) begin\n", .{source_id});
        try writer.print("    {s} <= null_value;\n", .{dest_id});
        try writer.print("    if is_data({s}) and payload({s}) = std_logic_vector(to_unsigned({d}, DATA_WIDTH)) then\n", .{ source_id, source_id, value });
        try writer.print("      {s} <= data_value(1);\n", .{dest_id});
        try writer.print("    elsif is_data({s}) then\n", .{source_id});
        try writer.print("      {s} <= data_value(0);\n", .{dest_id});
        try writer.print("    end if;\n  end process;\n", .{});
        return true;
    }

    return false;
}


fn placeName(allocator: std.mem.Allocator, arg: network.Arg) ![]const u8 {
    const raw_name = switch (arg.kind) {
        .place => if (arg.name.len > 0) arg.name else arg.text,
        .literal, .expression => arg.text,
        .group => arg.text,
    };
    return try sanitizeName(allocator, raw_name);
}


fn isBoundaryPort(def: network.Definition, name: []const u8) bool {
    for (def.sources) |src| {
        if (argContainsName(src, name)) return true;
    }
    for (def.destinations) |dest| {
        if (argContainsName(dest, name)) return true;
    }
    return false;
}

fn scopedDefinitionName(
    allocator: std.mem.Allocator,
    scope: []const u8,
    name: []const u8,
) ![]u8 {
    if (scope.len == 0) return sanitizeName(allocator, name);
    const local_name = try sanitizeName(allocator, name);
    defer allocator.free(local_name);
    return std.fmt.allocPrint(allocator, "{s}_{s}", .{ scope, local_name });
}

fn invocationDefinitionName(
    allocator: std.mem.Allocator,
    def: network.Definition,
    scope: []const u8,
    name: []const u8,
) ![]u8 {
    for (def.contained) |contained| {
        if (std.ascii.eqlIgnoreCase(contained.name, name)) {
            return scopedDefinitionName(allocator, scope, name);
        }
    }
    return sanitizeName(allocator, name);
}


fn writeIntermediatePlaceSignal(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
    intermediate_names: *std.ArrayListUnmanaged([]const u8),
    arg: network.Arg,
) !void {
    switch (arg.kind) {
        .group => if (arg.group) |grp| {
            for (grp.places) |child| {
                try writeIntermediatePlaceSignal(allocator, writer, def, intermediate_names, child);
            }
        },
        .place => {
            const raw_name = arg.name;
            if (raw_name.len == 0) return;

            // Avoid declaring signals for ports already declared on the boundary
            if (isBoundaryPort(def, raw_name)) return;

            // Avoid duplicate declarations
            for (intermediate_names.items) |existing| {
                if (std.mem.eql(u8, existing, raw_name)) return;
            }

            const signal_id = try sanitizeName(allocator, raw_name);
            defer allocator.free(signal_id);

            try intermediate_names.append(allocator, try allocator.dupe(u8, raw_name));
            // Same width fix as writeBoundaryPorts above — must match
            // ncl_signal, not a bare DATA_WIDTH vector.
            try writer.print("  signal {s} : ncl_signal;\n", .{signal_id});
            try writer.print("  signal {s}_valid : std_logic;\n", .{signal_id});
        },
        else => {},
    }
}

fn writeIntermediateSignal(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
    names: *std.ArrayListUnmanaged([]const u8),
    raw_name: []const u8,
) !void {
    if (raw_name.len == 0 or isDefinitionPort(def, raw_name)) return;
    for (names.items) |name| if (std.ascii.eqlIgnoreCase(name, raw_name)) return;
    try names.append(allocator, try allocator.dupe(u8, raw_name));
    const id = try sanitizeName(allocator, raw_name);
    defer allocator.free(id);
    try writer.print("  signal {s} : ncl_signal;\n", .{id});
}

fn writeDollarReferenceSignals(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
    names: *std.ArrayListUnmanaged([]const u8),
    expression: []const u8,
) !void {
    var i: usize = 0;
    while (i < expression.len) {
        if (expression[i] != '$') {
            i += 1;
            continue;
        }
        i += 1;
        const start = i;
        while (i < expression.len and (std.ascii.isAlphanumeric(expression[i]) or expression[i] == '_')) i += 1;
        if (i > start) try writeIntermediateSignal(allocator, writer, def, names, expression[start..i]);
    }
}

fn isDefinitionPort(def: network.Definition, name: []const u8) bool {
    return argListContainsName(def.sources, name) or argListContainsName(def.destinations, name);
}

fn argListContainsName(args: []const network.Arg, name: []const u8) bool {
    // Mirrors writeBoundaryPorts/boundaryCount's own recursion —
    // without it, any source/destination nested inside a bracket or
    // mutex group ("[{A0<> A1<>}]", "{$0 $1}", etc. — a very common
    // shape) is invisible here, so the fill/$-reference declaration
    // code below wrongly re-declares it as a fresh internal signal,
    // colliding with the port writeBoundaryPorts already emitted.
    for (args) |arg| {
        switch (arg.kind) {
            .group => if (arg.group) |grp| {
                if (argListContainsName(grp.places, name)) return true;
            },
            .place => if (std.ascii.eqlIgnoreCase(arg.name, name)) return true,
            else => {},
        }
    }
    return false;
}

// Tests

test "boundaryCount calculates scalar and group places correctly" {
    //const allocator = std.testing.allocator;

    // Create mock network args to test boundary counting
    const arg_place = network.Arg{
        .kind = .place,
        .name = "input_a",
    };
    
    // Test a single place
    const single_args = [_]network.Arg{arg_place};
    try std.testing.expectEqual(@as(usize, 1), boundaryCount(&single_args));

    // Test a group containing multiple places
    var group_places = [_]network.Arg{
        .{ .kind = .place, .name = "p1" },
        .{ .kind = .place, .name = "p2" },
    };
    const group_arg = network.Arg{
        .kind = .group,
        .group = .{
            .kind = .bundle,
            .places = &group_places,
        },
    };
    
    const group_args = [_]network.Arg{group_arg};
    try std.testing.expectEqual(@as(usize, 2), boundaryCount(&group_args));
}

test "argToText extracts expected string representations" {
    // 1. Place with name
    const place_arg = network.Arg{
        .kind = .place,
        .name = "foo",
        .text = "",
    };
    try std.testing.expectEqualSlices(u8, "foo", argToText(place_arg));

    // 2. Literal text
    const literal_arg = network.Arg{
        .kind = .literal,
        .name = "",
        .text = "42",
    };
    try std.testing.expectEqualSlices(u8, "42", argToText(literal_arg));
}

test "argContainsName checks nested structures" {
    var group_places = [_]network.Arg{
        .{ .kind = .place, .name = "target_place" },
    };
    const nested_group = network.Arg{
        .kind = .group,
        .group = .{
            .kind = .bundle,
            .places = &group_places,
        },
    };

    // Should find the name nested inside the group
    try std.testing.expect(argContainsName(nested_group, "target_place"));
    // Should return false for missing names
    try std.testing.expect(!argContainsName(nested_group, "nonexistent"));
   
}