// Responsibility: Orchestrates the core writeDefinition loop,
// connecting the definitions, ROM lookups, and delegating to the modules in export/.

const std = @import("std");
const network = @import("../network.zig");
const sanitizer = @import("sanitizer.zig");
const sanitizeName = sanitizer.sanitizeName;
const constants = @import("constants.zig");
const lookup = @import("lookup.zig");
pub const boundary = @import("export/boundary.zig");
pub const invocation = @import("export/invocation.zig");
const signal = @import("export/expression_signals.zig");
pub const network_entity = @import("export/network_entity.zig");
const component = @import("export/component.zig");
pub const value_transform = @import("../value_transform.zig"); // shared: AST shape + validation
const transform_emit = @import("export/value_transform.zig");  // VHDL-specific emission only
pub const rom_lookup = @import("export/rom_lookup.zig");

/// Emits a VHDL entity and architecture body for a single MatterScript definition,
/// normalizing destination defaults and identifiers, and recursively processing any
/// nested child definitions.
pub fn writeDefinition(
    allocator: std.mem.Allocator,
    writer: anytype,
    raw_def: network.Definition,
    scope: []const u8,
) !void {
    if (value_transform.isValueTransformRule(raw_def)) return;
    if (boundary.shouldSkipSpatialGeometry(raw_def)) return;

    var def = try boundary.normalizeReturnDestinations(allocator, raw_def);
    def = try sanitizer.normalizeDefinitionIdentifiers(allocator, def);

    const def_id = try invocation.scopedDefinitionName(allocator, scope, def.name);
    defer allocator.free(def_id);

    try writer.print(
        \\-- generated by MatterScript IPL
        \\-- definition: {s}
        \\library ieee;
        \\use ieee.std_logic_1164.all;
        \\use ieee.numeric_std.all;
        \\use work.matterscript_ncl.all;
        \\
        \\
    , .{def.name});

    try network_entity.writeEntityHeader(allocator, writer, def, def_id);

    // 1. Write children/contained definitions first (so they are declared before instantiation)
    for (def.contained) |contained| {
        if (contained.name.len == 0 or std.ascii.isDigit(contained.name[0])) continue;
        if (value_transform.isValueTransformRule(contained)) continue;
        try writer.print("\n", .{});

        const child_scope = try invocation.scopedDefinitionName(allocator, def_id, contained.name);
        defer allocator.free(child_scope);

        try writeDefinition(allocator, writer, contained, def_id);
    }

    // 2. Then write the parent definition/architecture that instantiates them
    try writer.print("architecture rtl of {s} is\n", .{def_id});

    // valid signals — one per source (input)
    for (def.sources) |src| {
        try boundary.writeBoundaryValidDeclarations(allocator, writer, src);
    }
    try writer.print("  signal complete   : std_logic;\n", .{});

    // per-table signals
    for (def.constants) |tbl| {
        const tbl_id = try sanitizeName(allocator, tbl.composed_name);
        defer allocator.free(tbl_id);
        const key_bits = lookup.countSources(tbl.composed_name) * constants.DATA_WIDTH;
        const val_bits = try lookup.tableValueWidth(allocator, tbl);
        try writer.print("  signal {s}_key   : std_logic_vector({d} downto 0);\n", .{ tbl_id, key_bits - 1 });
        try writer.print("  signal {s}_data  : std_logic_vector({d} downto 0);\n", .{ tbl_id, val_bits - 1 });
        try writer.print("  signal {s}_valid : std_logic;\n", .{tbl_id});
    }

    var intermediate_names: std.ArrayListUnmanaged([]const u8) = .empty;
    for (def.resolution) |stmt| {
        switch (stmt) {
            .fill => |fill| {
                try signal.writeIntermediateSignal(allocator, writer, def, &intermediate_names, fill.dest_name);
                try signal.writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, fill.expr);
            },
            .invoke => |inv| {
                for (inv.destinations) |dest| {
                    try signal.writeIntermediatePlaceSignal(allocator, writer, def, &intermediate_names, dest);
                }
                for (inv.sources) |src| {
                    try signal.writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, invocation.argToText(src));
                }
            },
            .pure_value => |value| try signal.writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, value),
            .directive => |d| {
                try writer.print("  -- @{s}({s}) (directive not yet interpreted)\n", .{ d.name, d.args });
            },
        }
    }

    const transform_rules = try value_transform.collectValueTransformRules(allocator, def);
    // boundary-port-collision check no longer needed here — validate.zig
    // already enforces it at parse time via this same shared module.

    for (transform_rules) |rule| {
        for (rule.inputs) |name| try signal.writeIntermediateSignal(allocator, writer, def, &intermediate_names, name);
        for (rule.targets) |name| try signal.writeIntermediateSignal(allocator, writer, def, &intermediate_names, name);
    }

    var component_names: std.ArrayListUnmanaged([]const u8) = .empty;
    for (def.resolution) |stmt| {
        if (stmt != .invoke) continue;
        const inv = stmt.invoke;
        var already_declared = false;
        for (component_names.items) |name| {
            if (std.ascii.eqlIgnoreCase(name, inv.name)) {
                already_declared = true;
                break;
            }
        }
        if (already_declared) continue;
        const name = try allocator.dupe(u8, inv.name);
        try component_names.append(allocator, name);
        const component_id = try invocation.invocationDefinitionName(allocator, def, scope, inv.name);
        defer allocator.free(component_id);
        try component.writeComponentDeclaration(writer, inv, component_id);
    }

    try invocation.writeInvocationSignals(writer, def);

    try writer.print("begin\n\n", .{});

    for (def.resolution, 0..) |stmt, invocation_index| {
        if (stmt != .invoke) continue;
        const inv = stmt.invoke;
        for (inv.sources, 0..) |arg, argument_index| {
            try invocation.writeInvocationArgument(allocator, writer, invocation_index, argument_index, arg);
        }
        for (inv.destinations, 0..) |output, output_index| {
            if (output.group == null and output.name.len != 0) continue;
            try writer.print("  invocation_{d}_output_{d} <= null_value;\n", .{ invocation_index, output_index });
        }
        try invocation.writeInvocationInstance(allocator, writer, def, def_id, inv, invocation_index);
    }

    // valid extraction from source places (inputs)
    try writer.print("  -- extract valid bits from source places (inputs)\n", .{});
    for (def.sources) |src| {
        try boundary.writeBoundaryValidAssignments(allocator, writer, src);
    }

    // completeness: AND of all source valids
    try writer.print("\n  -- complete when all source places are valid\n", .{});
    var valid_exprs: std.ArrayListUnmanaged([]const u8) = .empty;
    defer {
        for (valid_exprs.items) |expr| allocator.free(expr);
        valid_exprs.deinit(allocator);
    }

    for (def.sources) |src| {
        var aw: std.Io.Writer.Allocating = .init(allocator);
        defer aw.deinit();

        try boundary.writeBoundaryValidExpression(allocator, &aw.writer, src);

        const trimmed = std.mem.trim(u8, aw.written(), " \t\r\n");
        if (trimmed.len > 0) {
            try valid_exprs.append(allocator, try allocator.dupe(u8, trimmed));
        }
    }

    if (valid_exprs.items.len == 0) {
        try writer.print("  complete <= '1';\n", .{});
    } else {
        try writer.print("  complete <= ", .{});
        for (valid_exprs.items, 0..) |expr, i| {
            if (i > 0) try writer.print(" and ", .{});
            try writer.print("{s}", .{expr});
        }
        try writer.print(";\n", .{});
    }

    try rom_lookup.writeKeyComposition(allocator, writer, def);
    try rom_lookup.writeRomLookupProcess(allocator, writer, def);

    try transform_emit.writeTransformRules(allocator, writer, transform_rules);

    try signal.writeDestinationFills(allocator, writer, def);

    try writer.print("\nend rtl;\n", .{});
}