// Responsibility: Orchestrates the core writeDefinition loop, 
// connecting the definitions, ROM lookups, and delegating to the modules in export/.

const std = @import("std");
const network = @import("../network.zig");
const sanitizer = @import("sanitizer.zig");
const sanitizeName = sanitizer.sanitizeName;
const constants = @import("constants.zig");
const lookup = @import("lookup.zig");
pub const boundary = @import("export/boundary.zig");
pub const invocation = @import("export/invocation.zig");
const signal = @import("export/expression_signals.zig");
pub const network_entity = @import("export/network_entity.zig");

const DATA_WIDTH = constants.DATA_WIDTH;


/// Emits a VHDL entity and architecture body for a single MatterScript definition,
/// normalizing destination defaults and identifiers, and recursively processing any
/// nested child definitions.
pub fn writeDefinition(
    allocator: std.mem.Allocator,
    writer: anytype,
    raw_def: network.Definition,
    scope: []const u8,
) !void {
    // §12.3.4 "Single Return to Place of Invocation" — if this
    // definition has no destination list at all, its resolution's
    // top-level fill(s) express the implicit return(s) instead,
    // whether unnamed (synthesize "result") or already named (e.g.
    // "out1" in "A[out1< $in >]"). Normalized ONCE here, into a
    // corrected copy of `def`, so every downstream use — component
    // declarations, intermediate signals, lookup tables, fill
    // emission — sees consistent data, instead of patching each call
    // site individually and risking missing one.
    var def = raw_def;
    if (def.destinations.len == 0) {
        var names: std.ArrayListUnmanaged([]const u8) = .empty;
        var normalized: std.ArrayListUnmanaged(network.Statement) = .empty;
        for (def.resolution) |stmt| {
            switch (stmt) {
                .fill => |raw_f| {
                    var f = raw_f;
                    if (f.dest_name.len == 0) f.dest_name = "result";
                    var have = false;
                    for (names.items) |n| {
                        if (std.mem.eql(u8, n, f.dest_name)) {
                            have = true;
                            break;
                        }
                    }
                    if (!have) try names.append(allocator, f.dest_name);
                    try normalized.append(allocator, .{ .fill = f });
                },
                else => try normalized.append(allocator, stmt),
            }
        }
        if (names.items.len > 0) {
            var dests: std.ArrayListUnmanaged(network.Arg) = .empty;
            for (names.items) |n| try dests.append(allocator, .{ .kind = .place, .name = n });
            def.destinations = try dests.toOwnedSlice(allocator);
            def.resolution = try normalized.toOwnedSlice(allocator);
        }
    }

    // IPL names are case-sensitive, whereas VHDL identifiers are not.  Give
    // every exact IPL spelling a stable, lowercase VHDL spelling before any
    // declaration or reference is emitted.  This is deliberately done to the
    // whole definition, rather than only to ports: `a` and `A` must remain
    // distinct in assignments, expression references, and intermediate
    // signals as well as in the entity interface.
    def = try sanitizer.normalizeDefinitionIdentifiers(allocator, def);

    {
        const def_id = try invocation.scopedDefinitionName(allocator, scope, def.name);
        defer allocator.free(def_id);
        try writer.print(
            \\-- generated by MatterScript IPL
            \\-- definition: {s}
            \\library ieee;
            \\use ieee.std_logic_1164.all;
            \\use ieee.numeric_std.all;
            \\use work.matterscript_ncl.all;
            \\
            \\
        , .{def.name});

        // entity
        const boundary_count = boundary.boundaryCount(def.sources) + boundary.boundaryCount(def.destinations);
        if (boundary_count == 0) {
            try writer.print("entity {s} is\nend {s};\n\n", .{ def_id, def_id });
        } else {
            try writer.print("entity {s} is\n  port(\n", .{def_id});
            // sources → inputs (tokens flow IN to the definition)
            var port_index: usize = 0;
            var port_names: std.ArrayListUnmanaged([]const u8) = .empty;
            for (def.sources) |src| {
                try boundary.writeBoundaryPorts(allocator, writer, src, "in", &port_index, boundary_count, &port_names);
            }

            // destinations → outputs (tokens flow OUT of the definition)
            for (def.destinations) |dest| {
                try boundary.writeBoundaryPorts(allocator, writer, dest, "out", &port_index, boundary_count, &port_names);
            }
            try writer.print("  );\nend {s};\n\n", .{def_id});
        }

        // 1. Write children/contained definitions first (so they are declared before instantiation)
        for (def.contained) |contained| {
            if (contained.name.len == 0 or std.ascii.isDigit(contained.name[0])) continue;
            try writer.print("\n", .{});

            // Compute this child's full scoped name using the current entity's name (def_id) as the parent scope
            const child_scope = try invocation.scopedDefinitionName(allocator, def_id, contained.name);
            defer allocator.free(child_scope);

            // Recursively write the child, passing its full scoped name as its def_id
            try writeDefinition(allocator, writer, contained, def_id);
        }

        // 2. Then write the parent definition/architecture that instantiates them
        try writer.print("architecture rtl of {s} is\n", .{def_id});

        // valid signals — one per source (input)
        for (def.sources) |src| {
            try boundary.writeBoundaryValidDeclarations(allocator, writer, src);
        }
        try writer.print("  signal complete   : std_logic;\n", .{});

        // per-table signals
        for (def.constants) |tbl| {
            const tbl_id = try sanitizeName(allocator, tbl.composed_name);
            defer allocator.free(tbl_id);
            const key_bits = lookup.countSources(tbl.composed_name) * DATA_WIDTH;
            const val_bits = try lookup.tableValueWidth(allocator, tbl);
            try writer.print("  signal {s}_key   : std_logic_vector({d} downto 0);\n", .{ tbl_id, key_bits - 1 });
            try writer.print("  signal {s}_data  : std_logic_vector({d} downto 0);\n", .{ tbl_id, val_bits - 1 });
            try writer.print("  signal {s}_valid : std_logic;\n", .{tbl_id});
        }

        var intermediate_names: std.ArrayListUnmanaged([]const u8) = .empty;
        for (def.resolution) |stmt| {
            switch (stmt) {
                .fill => |fill| {
                    // A fill's destination (e.g. "p0" in "p0<point(...)>")
                    // is only a boundary port when it's actually
                    // declared in sources/destinations — otherwise it's
                    // a purely internal place that still needs a
                    // signal declared for it, or ghdl reports "no
                    // declaration for <name>" on the assignment below.
                    // Any $-referenced names inside the expression
                    // itself need the same treatment (mirroring the
                    // .invoke and .pure_value cases here).
                    try signal.writeIntermediateSignal(allocator, writer, def, &intermediate_names, fill.dest_name);
                    try signal.writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, fill.expr);
                },
                .invoke => |inv| {
                    for (inv.destinations) |dest| {
                        try signal.writeIntermediatePlaceSignal(allocator, writer, def, &intermediate_names, dest);
                    }
                    for (inv.sources) |src| {
                        try signal.writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, invocation.argToText(src));
                    }
                },
                .pure_value => |value| try signal.writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, value),
                .directive => |d| {
                    try writer.print("  -- @{s}({s}) (directive not yet interpreted)\n", .{ d.name, d.args });
                },
            }
        }

        var component_names: std.ArrayListUnmanaged([]const u8) = .empty;
        for (def.resolution) |stmt| {
            if (stmt != .invoke) continue;
            const inv = stmt.invoke;
            var already_declared = false;
            for (component_names.items) |name| {
                if (std.ascii.eqlIgnoreCase(name, inv.name)) {
                    already_declared = true;
                    break;
                }
            }
            if (already_declared) continue;
            const name = try allocator.dupe(u8, inv.name);
            try component_names.append(allocator, name);
            const component_id = try invocation.invocationDefinitionName(allocator, def, scope, inv.name);
            defer allocator.free(component_id);
            try writeComponentDeclaration(writer, inv, component_id);
        }

        for (def.resolution, 0..) |stmt, invocation_index| {
            if (stmt != .invoke) continue;
            const inv = stmt.invoke;
            for (inv.sources, 0..) |_, argument_index| {
                try writer.print("  signal invocation_{d}_arg_{d} : ncl_signal;\n", .{ invocation_index, argument_index });
            }
            for (inv.destinations, 0..) |output, output_index| {
                if (output.group == null and output.name.len != 0) continue;
                try writer.print("  signal invocation_{d}_output_{d} : ncl_signal;\n", .{ invocation_index, output_index });
            }
        }
        try writer.print("begin\n\n", .{});

        for (def.resolution, 0..) |stmt, invocation_index| {
            if (stmt != .invoke) continue;
            const inv = stmt.invoke;
            for (inv.sources, 0..) |arg, argument_index| {
                try invocation.writeInvocationArgument(allocator, writer, invocation_index, argument_index, arg);
            }
            for (inv.destinations, 0..) |output, output_index| {
                if (output.group == null and output.name.len != 0) continue;
                try writer.print("  invocation_{d}_output_{d} <= null_value;\n", .{ invocation_index, output_index });
            }
            try invocation.writeInvocationInstance(allocator, writer, def, def_id, inv, invocation_index);
        }

        // valid extraction from source places (inputs)
        try writer.print("  -- extract valid bits from source places (inputs)\n", .{});
        for (def.sources) |src| {
            try boundary.writeBoundaryValidAssignments(allocator, writer, src);
        }

        // completeness: AND of all source valids
        try writer.print("\n  -- complete when all source places are valid\n", .{});

        var valid_exprs: std.ArrayListUnmanaged([]const u8) = .empty;
        defer {
            for (valid_exprs.items) |expr| allocator.free(expr);
            valid_exprs.deinit(allocator);
        }

        for (def.sources) |src| {
            var aw: std.Io.Writer.Allocating = .init(allocator);
            defer aw.deinit();

            try boundary.writeBoundaryValidExpression(allocator, &aw.writer, src);

            const trimmed = std.mem.trim(u8, aw.written(), " \t\r\n");
            if (trimmed.len > 0) {
                try valid_exprs.append(allocator, try allocator.dupe(u8, trimmed));
            }
        }

        if (valid_exprs.items.len == 0) {
            try writer.print("  complete <= '1';\n", .{});
        } else {
            try writer.print("  complete <= ", .{});
            for (valid_exprs.items, 0..) |expr, i| {
                if (i > 0) try writer.print(" and ", .{});
                try writer.print("{s}", .{expr});
            }
            try writer.print(";\n", .{});
        }

        // key composition
        for (def.constants) |tbl| {
            const tbl_id = try sanitizeName(allocator, tbl.composed_name);
            defer allocator.free(tbl_id);
            try writer.print("\n  -- key composition for {s}\n", .{tbl.composed_name});
            try writer.print("  {s}_key <= ", .{tbl_id});
            var i: usize = 0;
            var first = true;
            const cn = tbl.composed_name;
            while (i < cn.len) {
                if (cn[i] == '$') {
                    i += 1;
                    const start = i;
                    while (i < cn.len and cn[i] != '$' and cn[i] != '(') i += 1;
                    const sname = cn[start..i];
                    if (!first) try writer.print(" & ", .{});
                    try writer.print("{s}(7 downto 1)", .{sname});
                    first = false;
                } else i += 1;
            }
            try writer.print(";\n", .{});
        }

        // ROM lookups
        for (def.constants) |tbl| {
            const tbl_id = try sanitizeName(allocator, tbl.composed_name);
            defer allocator.free(tbl_id);
            const val_bits = try lookup.tableValueWidth(allocator, tbl);

            try writer.print("\n  -- ROM lookup for {s}\n", .{tbl.composed_name});
            try writer.print("  process({s}_key, complete) begin\n", .{tbl_id});
            try writer.print("    {s}_data  <= (others => '0');\n", .{tbl_id});
            try writer.print("    {s}_valid <= '0';\n", .{tbl_id});
            try writer.print("    if complete = '1' then\n", .{});
            try writer.print("      case {s}_key is\n", .{tbl_id});

            switch (tbl.kind) {
                .explicit => |entries| {
                    var key_buf: [128]u8 = undefined;
                    var val_buf: [64]u8 = undefined;
                    for (entries) |entry| {
                        var key_pos: usize = 0;
                        for (entry.key) |ch| {
                            const dv: u64 = ch - '0';
                            const seg = lookup.binStr(key_buf[key_pos..], dv, DATA_WIDTH);
                            key_pos += seg.len;
                        }
                        const key_str = key_buf[0..key_pos];
                        const val_int = std.fmt.parseInt(u64, entry.value, 10) catch 0;
                        const val_str = lookup.binStr(&val_buf, val_int, val_bits);
                        try writer.print("        when \"{s}\" => {s}_data <= \"{s}\"; {s}_valid <= '1';\n", .{ key_str, tbl_id, val_str, tbl_id });
                    }
                },
                .generate => {
                    // TODO
                },
            }

            try writer.print("        when others => null;\n", .{});
            try writer.print("      end case;\n    end if;\n  end process;\n", .{});
        }

        // destination fills (outputs)
        try writer.print("\n  -- destination fills (outputs)\n", .{});
        if (!try lookup.writeContainedLookupTable(allocator, writer, def)) {
            for (def.resolution) |stmt| {
                switch (stmt) {
                    .fill => |f| {
                        const literal = std.fmt.parseInt(u64, std.mem.trim(u8, f.expr, " \t\r\n"), 10) catch null;
                        if (literal) |value| {
                            const dest_id = try sanitizeName(allocator, f.dest_name);
                            defer allocator.free(dest_id);
                            try writer.print("  {s} <= data_value({d});\n", .{ dest_id, value });
                        } else if (!try signal.writeExpressionFill(allocator, writer, f)) {
                            const dest_id = try sanitizeName(allocator, f.dest_name);
                            defer allocator.free(dest_id);
                            try writer.print("  {s} <= null_value;\n", .{dest_id});
                        }
                    },
                    .invoke => |inv| {
                        _ = inv;
                    },
                    .pure_value => |v| {
                        try writer.print("  -- TODO: pure value expression {s} (not a recognized lookup-table shape)\n", .{v});
                    },
                    .directive => |d| {
                        try writer.print("  -- @{s}({s}) (directive not yet interpreted)\n", .{ d.name, d.args });
                    },
                }
            }
        }

        try writer.print("\nend rtl;\n", .{});
    }
}

fn writeComponentDeclaration(
    writer: anytype,
    inv: network.Invocation,
    component_id: []const u8,
) !void {
    const port_count = inv.sources.len + inv.destinations.len;
    if (port_count == 0) {
        try writer.print("  component {s}\n  end component;\n\n", .{component_id});
        return;
    }

    try writer.print("  component {s}\n    port(\n", .{component_id});

    for (inv.sources, 0..) |_, i| {
        const last = (i + 1 == port_count);
        try writer.print("      arg_{d} : in ncl_signal{s}\n", .{ i, if (last) "" else ";" });
    }
    for (inv.destinations, 0..) |_, i| {
        const absolute_i = i + inv.sources.len;
        const last = (absolute_i + 1 == port_count);
        try writer.print("      output_{d} : out ncl_signal{s}\n", .{ i, if (last) "" else ";" });
    }
    try writer.print("    );\n  end component;\n\n", .{});
}


