// verify_examples.zig
// Parses every example under examples/docs/<TAG-ID>/*.ms.ipl, attempts
// VHDL emission and a GHDL syntax check, and compares the outcome
// against the expected implementation_status recorded in status.json
// (generated by weave from Linear's Implemented/Partial/Spec Only
// labels).
//
// Also supports running GHDL cycle-accurate simulations for examples
// where simulation_requested is set to true in status.json.

const std = @import("std");

const matterscript = @import("matterscript");
const ipl_parser = matterscript.ipl_parser;
const ipl_export_vhdl = matterscript.ipl_export_vhdl;

const ExampleResult = enum { pass, fail, expected_fail, unexpected_pass };

const StatusEntry = struct {
    implementation_status: ?[]const u8,
    simulation_requested: bool,
};

const ExampleRow = struct {
    tag: []const u8,
    path: []const u8,
    expected_status: ?[]const u8,
    simulation_requested: bool,
    parse_ok: bool,
    ghdl_ok: bool,
    simulation_ok: bool,
    simulation_error: ?[]const u8,
    result: ExampleResult,
};

fn getStatusEntry(map: std.StringHashMap(StatusEntry), tag: []const u8) StatusEntry {
    return map.get(tag) orelse .{ .implementation_status = null, .simulation_requested = false };
}

fn lessThanByTag(_: void, a: ExampleRow, b: ExampleRow) bool {
    return std.mem.lessThan(u8, a.tag, b.tag);
}

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);
    const io = init.io;

    var status_path: []const u8 = "docs/generated/linear/status.json";
    var output_path: []const u8 = "docs/generated/linear/verify_results.md";
    var examples: std.ArrayListUnmanaged(struct { tag: []const u8, path: []const u8 }) = .empty;

    var i: usize = 1;
    while (i < args.len) : (i += 1) {
        if (std.mem.eql(u8, args[i], "--status") and i + 1 < args.len) {
            status_path = args[i + 1];
            i += 1;
        } else if (std.mem.eql(u8, args[i], "--output") and i + 1 < args.len) {
            output_path = args[i + 1];
            i += 1;
        } else if (std.mem.eql(u8, args[i], "--example") and i + 2 < args.len) {
            try examples.append(arena, .{ .tag = args[i + 1], .path = args[i + 2] });
            i += 2;
        }
    }

    const status_map = try readStatusManifest(arena, io, status_path);

    std.Io.Dir.cwd().createDir(io, ".verify_scratch", .default_dir) catch |err| switch (err) {
        error.PathAlreadyExists => {},
        else => return err,
    };

    var rows: std.ArrayListUnmanaged(ExampleRow) = .empty;

    for (examples.items) |ex| {
        const entry = getStatusEntry(status_map, ex.tag);
        const expected = entry.implementation_status;
        const sim_requested = entry.simulation_requested;

        const source = std.Io.Dir.cwd().readFileAlloc(io, ex.path, arena, .limited(1024 * 1024)) catch {
            try rows.append(arena, .{
                .tag = ex.tag,
                .path = ex.path,
                .expected_status = expected,
                .simulation_requested = sim_requested,
                .parse_ok = false,
                .ghdl_ok = false,
                .simulation_ok = false,
                .simulation_error = null,
                .result = .fail,
            });
            continue;
        };

        const net = ipl_parser.parseWithTag(arena, source, ex.tag) catch {
            try rows.append(arena, .{
                .tag = ex.tag,
                .path = ex.path,
                .expected_status = expected,
                .simulation_requested = sim_requested,
                .parse_ok = false,
                .ghdl_ok = false,
                .simulation_ok = false,
                .simulation_error = null,
                .result = classify(expected, false, false, sim_requested, false),
            });
            continue;
        };

        // Emit VHDL into memory, then to a scratch file GHDL can read.
        var vhdl_body: std.ArrayList(u8) = .empty;
        defer vhdl_body.deinit(arena);
        var vhdl_writer: std.Io.Writer.Allocating = .fromArrayList(arena, &vhdl_body);

        const emit_ok = blk: {
            ipl_export_vhdl.write(arena, &vhdl_writer.writer, net) catch break :blk false;
            break :blk true;
        };

        var ghdl_ok = false;
        var simulation_ok = false;
        var simulation_error: ?[]const u8 = null;

        if (emit_ok) {
            vhdl_body = vhdl_writer.toArrayList();
            const basename = std.fs.path.basename(ex.path);
            const vhd_path = try std.fmt.allocPrint(arena, ".verify_scratch/{s}-{s}.vhd", .{ ex.tag, basename });

            var vhd_file = try std.Io.Dir.cwd().createFile(io, vhd_path, .{});
            {
                var buf: [8192]u8 = undefined;
                var w = vhd_file.writer(io, &buf);
                try w.interface.writeAll(vhdl_body.items);
                try w.interface.flush();
            }
            vhd_file.close(io);

            ghdl_ok = runGhdlSyntaxCheck(arena, io, vhd_path);

            if (ghdl_ok and sim_requested) {
                const tb_path = try getTestbenchPath(arena, ex.path);
                const sim_res = runGhdlSimulation(arena, io, vhd_path, tb_path);
                simulation_ok = sim_res.ok;
                simulation_error = sim_res.err_msg;
            }
        }

        try rows.append(arena, .{
            .tag = ex.tag,
            .path = ex.path,
            .expected_status = expected,
            .simulation_requested = sim_requested,
            .parse_ok = true,
            .ghdl_ok = ghdl_ok,
            .simulation_ok = simulation_ok,
            .simulation_error = simulation_error,
            .result = classify(expected, true, ghdl_ok, sim_requested, simulation_ok),
        });
    }

    std.mem.sort(ExampleRow, rows.items, {}, lessThanByTag);
    try writeMarkdownReport(io, output_path, rows.items);

    // Print captured simulation errors to stderr prior to the table output
    var printed_header = false;
    for (rows.items) |row| {
        if (row.simulation_error) |err_msg| {
            if (!printed_header) {
                std.debug.print("\n================================================================================\n", .{});
                std.debug.print("                         CAPTURE SIMULATION FAILURES                            \n", .{});
                std.debug.print("================================================================================\n", .{});
                printed_header = true;
            }
            std.debug.print("❌ [{s}] Simulation Failure:\n{s}\n", .{ row.tag, err_msg });
        }
    }
    if (printed_header) {
        std.debug.print("================================================================================\n", .{});
    }

    printTable(rows.items);
}

/// Derive the testbench path by replacing `.ms.ipl` with `.tb.vhd` in the example path.
fn getTestbenchPath(allocator: std.mem.Allocator, ex_path: []const u8) ![]const u8 {
    if (std.mem.endsWith(u8, ex_path, ".ms.ipl")) {
        const prefix = ex_path[0 .. ex_path.len - 7];
        return std.fmt.allocPrint(allocator, "{s}.tb.vhd", .{prefix});
    }
    // Fallback if it doesn't end with .ms.ipl
    const dirname = std.fs.path.dirname(ex_path) orelse "";
    const basename = std.fs.path.basename(ex_path);
    const stem = if (std.mem.lastIndexOf(u8, basename, ".")) |idx| basename[0..idx] else basename;
    return std.fmt.allocPrint(allocator, "{s}/{s}.tb.vhd", .{ dirname, stem });
}

/// Derive the VHDL entity name from the testbench path (sanitizing dots and dashes to underscores).
fn getEntityName(allocator: std.mem.Allocator, tb_path: []const u8) ![]const u8 {
    const basename = std.fs.path.basename(tb_path);
    const stem = if (std.mem.lastIndexOf(u8, basename, ".")) |idx| basename[0..idx] else basename;
    const buf = try allocator.dupe(u8, stem);
    for (buf) |*c| {
        if (c.* == '.' or c.* == '-') {
            c.* = '_';
        }
    }
    return buf;
}

/// Persist the report instead of relying on shell redirection. The console
/// table uses std.debug (stderr), so redirecting stdout previously created an
/// empty Markdown file.
fn writeMarkdownReport(io: std.Io, path: []const u8, rows: []const ExampleRow) !void {
    var file = try std.Io.Dir.cwd().createFile(io, path, .{});
    defer file.close(io);

    var buffer: [8192]u8 = undefined;
    var writer = file.writer(io, &buffer);
    const w = &writer.interface;

    var ok_count: usize = 0;
    var unexpected_count: usize = 0;
    for (rows) |row| {
        if (row.result == .pass or row.result == .expected_fail) ok_count += 1 else unexpected_count += 1;
    }

    try w.writeAll("# Example verification results\n\n");
    try w.print("{d} expected outcomes, {d} unexpected outcomes.\n\n", .{ ok_count, unexpected_count });
    try w.writeAll("| Issue | Example | Expected | Parse | GHDL | Simulate | Result |\n");
    try w.writeAll("| --- | --- | --- | --- | --- | --- | --- |\n");

    for (rows) |row| {
        const expected = row.expected_status orelse "-";
        const parse = if (row.parse_ok) "ok" else "FAIL";
        const ghdl = if (!row.parse_ok) "-" else if (row.ghdl_ok) "ok" else "FAIL";
        const simulate = if (!row.simulation_requested) "-" else if (row.simulation_ok) "ok" else "FAIL";
        const result = switch (row.result) {
            .pass => "✅ PASS",
            .fail => "❌ FAIL",
            .expected_fail => "⬛ expected fail",
            .unexpected_pass => "🟡 unexpected pass",
        };
        try w.print("| {s} | {s} | {s} | {s} | {s} | {s} | {s} |\n", .{
            row.tag, std.fs.path.basename(row.path), expected, parse, ghdl, simulate, result,
        });
    }
    try w.flush();
}

fn classify(expected: ?[]const u8, parse_ok: bool, ghdl_ok: bool, simulation_requested: bool, simulation_ok: bool) ExampleResult {
    const passed = parse_ok and ghdl_ok and (!simulation_requested or simulation_ok);
    const expects_pass = expected != null and std.mem.eql(u8, expected.?, "Implemented");

    if (expects_pass) return if (passed) .pass else .fail;
    return if (passed) .unexpected_pass else .expected_fail;
}

fn runGhdlSyntaxCheck(allocator: std.mem.Allocator, io: std.Io, vhd_path: []const u8) bool {
    const package_result = std.process.run(allocator, io, .{
        .argv = &.{ "ghdl", "-a", "--std=08", "src/stdlib/ncl/matterscript_ncl.vhd" },
    }) catch |err| {
        std.debug.print("  [{s}] failed to spawn ghdl for package analysis: {s}\n", .{ vhd_path, @errorName(err) });
        return false;
    };
    defer allocator.free(package_result.stdout);
    defer allocator.free(package_result.stderr);
    switch (package_result.term) {
        .exited => |code| if (code != 0) {
            std.debug.print("  [{s}] ncl package analysis failed:\n{s}\n", .{ vhd_path, package_result.stderr });
            return false;
        },
        else => {
            std.debug.print("  [{s}] ncl package analysis did not exit normally\n", .{vhd_path});
            return false;
        },
    }

    const result = std.process.run(allocator, io, .{
        .argv = &.{ "ghdl", "-s", "--std=08", vhd_path },
    }) catch |err| {
        std.debug.print("  [{s}] failed to spawn ghdl for syntax check: {s}\n", .{ vhd_path, @errorName(err) });
        return false;
    };
    defer allocator.free(result.stdout);
    defer allocator.free(result.stderr);

    const ok = switch (result.term) {
        .exited => |code| code == 0,
        else => false,
    };
    if (!ok) {
        std.debug.print("  [{s}] ghdl syntax check failed:\n{s}\n", .{ vhd_path, result.stderr });
    }
    return ok;
}

const SimulationResult = struct {
    ok: bool,
    err_msg: ?[]const u8,
};

fn runGhdlSimulation(allocator: std.mem.Allocator, io: std.Io, vhd_path: []const u8, tb_path: []const u8) SimulationResult {
    // 1. Analyze stdlib package
    std.debug.print("  [{s}] Running GHDL simulation for testbench {s} (design {s})\n", .{ tb_path, tb_path, vhd_path });
    const package_result = std.process.run(allocator, io, .{
        .argv = &.{ "ghdl", "-a", "--std=08", "src/stdlib/ncl/matterscript_ncl.vhd" },
    }) catch |err| {
        const msg = std.fmt.allocPrint(allocator, "failed to spawn ghdl for package analysis: {s}", .{@errorName(err)}) catch return .{ .ok = false, .err_msg = "failed to spawn" };
        return .{ .ok = false, .err_msg = msg };
    };
    defer allocator.free(package_result.stdout);
    defer allocator.free(package_result.stderr);
    if (package_result.term != .exited or package_result.term.exited != 0) {
        const msg = std.fmt.allocPrint(allocator, "ncl package analysis failed:\n{s}", .{package_result.stderr}) catch return .{ .ok = false, .err_msg = "ncl package analysis failed" };
        return .{ .ok = false, .err_msg = msg };
    }

    // 2. Analyze the generated VHDL design unit
    const des_result = std.process.run(allocator, io, .{
        .argv = &.{ "ghdl", "-a", "--std=08", vhd_path },
    }) catch |err| {
        const msg = std.fmt.allocPrint(allocator, "failed to spawn ghdl for design analysis ({s}): {s}", .{ vhd_path, @errorName(err) }) catch return .{ .ok = false, .err_msg = "spawn error" };
        return .{ .ok = false, .err_msg = msg };
    };
    defer allocator.free(des_result.stdout);
    defer allocator.free(des_result.stderr);
    if (des_result.term != .exited or des_result.term.exited != 0) {
        const msg = std.fmt.allocPrint(allocator, "simulation design analysis failed:\n{s}", .{des_result.stderr}) catch return .{ .ok = false, .err_msg = "design analysis failed" };
        return .{ .ok = false, .err_msg = msg };
    }

    // 3. Analyze the testbench file
    const tb_result = std.process.run(allocator, io, .{
        .argv = &.{ "ghdl", "-a", "--std=08", tb_path },
    }) catch |err| {
        const msg = std.fmt.allocPrint(allocator, "failed to spawn ghdl for testbench analysis ({s}): {s}", .{ tb_path, @errorName(err) }) catch return .{ .ok = false, .err_msg = "spawn error" };
        return .{ .ok = false, .err_msg = msg };
    };
    defer allocator.free(tb_result.stdout);
    defer allocator.free(tb_result.stderr);
    if (tb_result.term != .exited or tb_result.term.exited != 0) {
        const msg = std.fmt.allocPrint(allocator, "simulation testbench analysis failed ({s}):\n{s}", .{ tb_path, tb_result.stderr }) catch return .{ .ok = false, .err_msg = "testbench analysis failed" };
        return .{ .ok = false, .err_msg = msg };
    }

    // 4. Elaborate testbench entity
    const entity_name = getEntityName(allocator, tb_path) catch {
        return .{ .ok = false, .err_msg = "failed to derive entity name" };
    };
    defer allocator.free(entity_name);

    const elab_result = std.process.run(allocator, io, .{
        .argv = &.{ "ghdl", "-e", "--std=08", entity_name },
    }) catch |err| {
        const msg = std.fmt.allocPrint(allocator, "failed to spawn ghdl for elaboration ({s}): {s}", .{ entity_name, @errorName(err) }) catch return .{ .ok = false, .err_msg = "spawn error" };
        return .{ .ok = false, .err_msg = msg };
    };
    defer allocator.free(elab_result.stdout);
    defer allocator.free(elab_result.stderr);
    if (elab_result.term != .exited or elab_result.term.exited != 0) {
        const msg = std.fmt.allocPrint(allocator, "simulation elaboration failed ({s}):\n{s}", .{ entity_name, elab_result.stderr }) catch return .{ .ok = false, .err_msg = "elaboration failed" };
        return .{ .ok = false, .err_msg = msg };
    }

    // 5. Execute simulation
    const run_result = std.process.run(allocator, io, .{
        .argv = &.{ "ghdl", "-r", "--std=08", entity_name, "--stop-time=10s" },
    }) catch |err| {
        const msg = std.fmt.allocPrint(allocator, "failed to spawn ghdl for execution: {s}", .{@errorName(err)}) catch return .{ .ok = false, .err_msg = "spawn error" };
        return .{ .ok = false, .err_msg = msg };
    };
    defer allocator.free(run_result.stdout);
    defer allocator.free(run_result.stderr);

    const ok = switch (run_result.term) {
        .exited => |code| code == 0,
        else => false,
    };

    if (!ok) {
        const msg = std.fmt.allocPrint(allocator, "simulation execution failed:\n{s}", .{run_result.stderr}) catch return .{ .ok = false, .err_msg = "execution failed" };
        return .{ .ok = false, .err_msg = msg };
    }

    return .{ .ok = true, .err_msg = null };
}

fn readStatusManifest(
    allocator: std.mem.Allocator,
    io: std.Io,
    path: []const u8,
) !std.StringHashMap(StatusEntry) {
    var map = std.StringHashMap(StatusEntry).init(allocator);

    const body = std.Io.Dir.cwd().readFileAlloc(io, path, allocator, .limited(1024 * 1024)) catch {
        std.debug.print("warning: could not read {s} — treating all examples as untagged\n", .{path});
        return map;
    };

    const parsed = std.json.parseFromSlice(std.json.Value, allocator, body, .{}) catch {
        std.debug.print("warning: could not parse {s}\n", .{path});
        return map;
    };
    defer parsed.deinit();

    var it = parsed.value.object.iterator();
    while (it.next()) |entry| {
        const tag = try allocator.dupe(u8, entry.key_ptr.*);
        const obj = entry.value_ptr.object;

        const impl = obj.get("implementation_status");
        const status: ?[]const u8 = if (impl) |i| switch (i) {
            .string => |s| try allocator.dupe(u8, s),
            else => null,
        } else null;

        const sim_req = obj.get("simulation_requested");
        const simulation_requested: bool = if (sim_req) |s| switch (s) {
            .bool => |b| b,
            .string => |str| std.mem.eql(u8, str, "true"),
            else => false,
        } else false;

        try map.put(tag, .{
            .implementation_status = status,
            .simulation_requested = simulation_requested,
        });
    }
    return map;
}

fn printTable(rows: []const ExampleRow) void {
    const separator = "-------------------------------------------------------------------------------------------------";

    std.debug.print("\n{s:<8} {s:<32} {s:<12} {s:<5} {s:<5} {s:<10} {s}\n", .{ "Issue", "example", "expected", "parse", "ghdl", "simulate", "result" });
    std.debug.print("{s}\n", .{separator});

    var pass_count: usize = 0;
    var fail_count: usize = 0;

    for (rows) |r| {
        const expected_str = r.expected_status orelse "-";
        const parse_str = if (r.parse_ok) "ok" else "FAIL";
        const ghdl_str = if (!r.parse_ok) "-" else if (r.ghdl_ok) "ok" else "FAIL";
        const sim_str = if (!r.simulation_requested) "-" else if (r.simulation_ok) "ok" else "FAIL";
        const result_str = switch (r.result) {
            .pass => "✅ PASS",
            .fail => "❌ FAIL",
            .expected_fail => "⬛ expected fail",
            .unexpected_pass => "🟡 unexpected pass",
        };
        if (r.result == .pass or r.result == .expected_fail) pass_count += 1 else fail_count += 1;

        std.debug.print("{s:<8} {s:<32} {s:<12} {s:<5} {s:<5} {s:<10} {s}\n", .{
            r.tag, std.fs.path.basename(r.path), expected_str, parse_str, ghdl_str, sim_str, result_str,
        });
    }

    std.debug.print("{s}\n", .{separator});
    std.debug.print("{d} ok, {d} unexpected\n\n", .{ pass_count, fail_count });
}