// verify_examples.zig
// Parses every example under examples/docs/<TAG-ID>/*.ms.il, attempts
// VHDL emission and a GHDL syntax check, and compares the outcome
// against the expected implementation_status recorded in status.json
// (generated by weave from Linear's Implemented/Partial/Spec Only
// labels).
//
// This is the "verify" tier only — parse + emit + GHDL syntax check.
// Verilator simulation needs per-example testbenches that don't exist
// yet, so cycle-accurate execution is out of scope here.

const std = @import("std");

const matterscript = @import("matterscript");
const il_parser = matterscript.il_parser;
const il_export_vhdl = matterscript.il_export_vhdl;

const ExampleResult = enum { pass, fail, expected_fail, unexpected_pass };

const ExampleRow = struct {
    tag: []const u8,
    path: []const u8,
    expected_status: ?[]const u8,
    parse_ok: bool,
    ghdl_ok: bool,
    result: ExampleResult,
};

/// StringHashMap(?T).get() returns ??T — doubly optional, since a
/// missing key and a key whose value is null both need collapsing
/// to a single "no expected status" case here.
fn expectedStatus(map: std.StringHashMap(?[]const u8), tag: []const u8) ?[]const u8 {
    return (map.get(tag) orelse null);
}

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);
    const io = init.io;

    var status_path: []const u8 = "docs/generated/linear/status.json";
    var examples: std.ArrayListUnmanaged(struct { tag: []const u8, path: []const u8 }) = .empty;

    var i: usize = 1;
    while (i < args.len) : (i += 1) {
        if (std.mem.eql(u8, args[i], "--status") and i + 1 < args.len) {
            status_path = args[i + 1];
            i += 1;
        } else if (std.mem.eql(u8, args[i], "--example") and i + 2 < args.len) {
            try examples.append(arena, .{ .tag = args[i + 1], .path = args[i + 2] });
            i += 2;
        }
    }

    const status_map = try readStatusManifest(arena, io, status_path);

    std.Io.Dir.cwd().createDir(io, ".verify_scratch", .default_dir) catch |err| switch (err) {
        error.PathAlreadyExists => {},
        else => return err,
    };

    var rows: std.ArrayListUnmanaged(ExampleRow) = .empty;

    for (examples.items) |ex| {
        const source = std.Io.Dir.cwd().readFileAlloc(io, ex.path, arena, .limited(1024 * 1024)) catch {
            try rows.append(arena, .{
                .tag = ex.tag,
                .path = ex.path,
                .expected_status = expectedStatus(status_map, ex.tag),
                .parse_ok = false,
                .ghdl_ok = false,
                .result = .fail,
            });
            continue;
        };

        const net = il_parser.parseWithTag(arena, source, ex.tag) catch {
            try rows.append(arena, .{
                .tag = ex.tag,
                .path = ex.path,
                .expected_status = expectedStatus(status_map, ex.tag),
                .parse_ok = false,
                .ghdl_ok = false,
                .result = classify(expectedStatus(status_map, ex.tag), false, false),
            });
            continue;
        };

        // Emit VHDL into memory, then to a scratch file GHDL can read.
        var vhdl_body: std.ArrayList(u8) = .empty;
        defer vhdl_body.deinit(arena);
        var vhdl_writer: std.Io.Writer.Allocating = .fromArrayList(arena, &vhdl_body);

        const emit_ok = blk: {
            il_export_vhdl.write(arena, &vhdl_writer.writer, net) catch break :blk false;
            break :blk true;
        };

        var ghdl_ok = false;
        if (emit_ok) {
            vhdl_body = vhdl_writer.toArrayList();
            const basename = std.fs.path.basename(ex.path);
            const vhd_path = try std.fmt.allocPrint(arena, ".verify_scratch/{s}-{s}.vhd", .{ ex.tag, basename });

            var vhd_file = try std.Io.Dir.cwd().createFile(io, vhd_path, .{});
            {
                var buf: [8192]u8 = undefined;
                var w = vhd_file.writer(io, &buf);
                try w.interface.writeAll(vhdl_body.items);
                try w.interface.flush();
            }
            vhd_file.close(io);

            ghdl_ok = runGhdlSyntaxCheck(arena, io, vhd_path);
        }

        try rows.append(arena, .{
            .tag = ex.tag,
            .path = ex.path,
            .expected_status = expectedStatus(status_map, ex.tag),
            .parse_ok = true,
            .ghdl_ok = ghdl_ok,
            .result = classify(expectedStatus(status_map, ex.tag), true, ghdl_ok),
        });
    }

    printTable(rows.items);
}

fn classify(expected: ?[]const u8, parse_ok: bool, ghdl_ok: bool) ExampleResult {
    const passed = parse_ok and ghdl_ok;
    const expects_pass = expected != null and std.mem.eql(u8, expected.?, "Implemented");

    if (expects_pass) return if (passed) .pass else .fail;
    return if (passed) .unexpected_pass else .expected_fail;
}

fn runGhdlSyntaxCheck(allocator: std.mem.Allocator, io: std.Io, vhd_path: []const u8) bool {
    const result = std.process.run(allocator, io, .{
        .argv = &.{ "ghdl", "-s", "--std=08", vhd_path },
    }) catch return false;
    defer allocator.free(result.stdout);
    defer allocator.free(result.stderr);

    return switch (result.term) {
        .exited => |code| code == 0,
        else => false,
    };
}

fn readStatusManifest(
    allocator: std.mem.Allocator,
    io: std.Io,
    path: []const u8,
) !std.StringHashMap(?[]const u8) {
    var map = std.StringHashMap(?[]const u8).init(allocator);

    const body = std.Io.Dir.cwd().readFileAlloc(io, path, allocator, .limited(1024 * 1024)) catch {
        std.debug.print("warning: could not read {s} — treating all examples as untagged\n", .{path});
        return map;
    };

    const parsed = std.json.parseFromSlice(std.json.Value, allocator, body, .{}) catch {
        std.debug.print("warning: could not parse {s}\n", .{path});
        return map;
    };
    defer parsed.deinit();

    var it = parsed.value.object.iterator();
    while (it.next()) |entry| {
        const tag = try allocator.dupe(u8, entry.key_ptr.*);
        const impl = entry.value_ptr.object.get("implementation_status").?;
        const status: ?[]const u8 = switch (impl) {
            .string => |s| try allocator.dupe(u8, s),
            else => null,
        };
        try map.put(tag, status);
    }
    return map;
}

fn printTable(rows: []const ExampleRow) void {
    const separator = "----------------------------------------------------------------------------------------------";

    std.debug.print("\n{s:<10} {s:<45} {s:<12} {s:<6} {s:<6} {s}\n", .{ "TAG", "example", "expected", "parse", "ghdl", "result" });
    std.debug.print("{s}\n", .{separator});

    var pass_count: usize = 0;
    var fail_count: usize = 0;

    for (rows) |r| {
        const expected_str = r.expected_status orelse "—";
        const parse_str = if (r.parse_ok) "ok" else "FAIL";
        const ghdl_str = if (!r.parse_ok) "—" else if (r.ghdl_ok) "ok" else "FAIL";
        const result_str = switch (r.result) {
            .pass => "✅ PASS",
            .fail => "❌ FAIL",
            .expected_fail => "⬛ expected fail",
            .unexpected_pass => "🟡 unexpected pass",
        };
        if (r.result == .pass or r.result == .expected_fail) pass_count += 1 else fail_count += 1;

        std.debug.print("{s:<10} {s:<45} {s:<12} {s:<6} {s:<6} {s}\n", .{
            r.tag, std.fs.path.basename(r.path), expected_str, parse_str, ghdl_str, result_str,
        });
    }

    std.debug.print("{s}\n", .{separator});
    std.debug.print("{d} ok, {d} unexpected\n\n", .{ pass_count, fail_count });
    
}
