// export_vhdl.zig
// VHDL emitter for MatterScript Invocation Language networks
//
// Port mapping (Fant authoritative grammar):
//   Definition source place  (name<>) → VHDL input  port  (tokens flow IN)
//   Definition destination place ($name) → VHDL output port (tokens flow OUT)
//
// Signal encoding:
//   signal[7:0] = { data[6:0], valid }
//   signal[0]   = valid bit  (1=DATA, 0=NULL)
//   signal[7:1] = 7-bit data payload (up to 127 distinct token values)

const std = @import("std");
const network = @import("network.zig");
const workspace = @import("../../common/workspace.zig");

const SIGNAL_WIDTH = 8;
const DATA_WIDTH = 7;

pub fn writeVhdlNetwork(
    io: std.Io,
    allocator: std.mem.Allocator,
    namespace: []const u8,
    net: network.Network,
    output_name: []const u8,
) !void {
    const output_path = try std.fmt.allocPrint(allocator, "../workspace/{s}/{s}", .{ namespace, output_name });
    defer allocator.free(output_path);

    var file = try std.Io.Dir.cwd().createFile(io, output_path, .{});
    defer file.close(io);

    var buffer: [65536]u8 = undefined;
    var writer = file.writer(io, &buffer);
    try write(allocator, &writer.interface, net);
    try writer.interface.flush();
}

pub fn write(allocator: std.mem.Allocator, writer: anytype, net: network.Network) !void {
    for (net.definitions) |def| {
        try writeDefinition(allocator, writer, def);
        try writer.print("\n", .{});
    }
}

fn writeDefinition(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
) !void {
    const def_id = try sanitizeName(allocator, def.name);
    defer allocator.free(def_id);
    try writer.print(
        \\-- generated by MatterScript IL
        \\-- definition: {s}
        \\library ieee;
        \\use ieee.std_logic_1164.all;
        \\use ieee.numeric_std.all;
        \\use work.matterscript_ncl.all;
        \\
        \\
    , .{def.name});

    // entity
    try writer.print("entity {s} is\n  port(\n", .{def_id});
    try writer.print("    clk : in  std_logic;\n", .{});
    try writer.print("    rst : in  std_logic;\n", .{});

    // sources → inputs (tokens flow IN to the definition)
    for (def.sources) |src| {
        const src_id = try placeName(allocator, src);
        defer allocator.free(src_id);
        try writer.print("    {s} : in  std_logic_vector({d} downto 0);  -- source place (input)\n", .{ src_id, SIGNAL_WIDTH - 1 });
    }

    // destinations → outputs (tokens flow OUT of the definition)
    for (def.destinations, 0..) |dest, i| {
        const dest_id = try placeName(allocator, dest);
        defer allocator.free(dest_id);
        const last = i == def.destinations.len - 1;
        try writer.print("    {s} : out std_logic_vector({d} downto 0){s}  -- destination place (output)\n", .{ dest_id, SIGNAL_WIDTH - 1, if (last) "" else ";" });
    }
    try writer.print("  );\nend {s};\n\n", .{def_id});

    // architecture
    try writer.print("architecture rtl of {s} is\n", .{def_id});

    // valid signals — one per source (input)
    for (def.sources) |src| {
        const src_id = try placeName(allocator, src);
        defer allocator.free(src_id);
        try writer.print("  signal {s}_valid : std_logic;\n", .{src_id});
    }
    try writer.print("  signal complete   : std_logic;\n", .{});

    // per-table signals
    for (def.constants) |tbl| {
        const tbl_id = try sanitizeName(allocator, tbl.composed_name);
        defer allocator.free(tbl_id);
        const key_bits = countSources(tbl.composed_name) * DATA_WIDTH;
        const val_bits = try tableValueWidth(allocator, tbl);
        try writer.print("  signal {s}_key   : std_logic_vector({d} downto 0);\n", .{ tbl_id, key_bits - 1 });
        try writer.print("  signal {s}_data  : std_logic_vector({d} downto 0);\n", .{ tbl_id, val_bits - 1 });
        try writer.print("  signal {s}_valid : std_logic;\n", .{tbl_id});
    }

    try writer.print("begin\n\n", .{});

    // valid extraction from source places (inputs)
    try writer.print("  -- extract valid bits from source places (inputs)\n", .{});
    for (def.sources) |src| {
        const src_id = try placeName(allocator, src);
        defer allocator.free(src_id);
        try writer.print("  {s}_valid <= {s}(0);\n", .{ src_id, src_id });
    }

    // completeness: AND of all source valids
    try writer.print("\n  -- complete when all source places are valid\n", .{});
    try writer.print("  complete <= ", .{});
    for (def.sources, 0..) |src, i| {
        if (i > 0) try writer.print(" and ", .{});
        const src_id = try placeName(allocator, src);
        defer allocator.free(src_id);
        try writer.print("{s}_valid", .{src_id});
    }
    try writer.print(";\n", .{});

    // key composition
    for (def.constants) |tbl| {
        const tbl_id = try sanitizeName(allocator, tbl.composed_name);
        defer allocator.free(tbl_id);
        try writer.print("\n  -- key composition for {s}\n", .{tbl.composed_name});
        try writer.print("  {s}_key <= ", .{tbl_id});
        var i: usize = 0;
        var first = true;
        const cn = tbl.composed_name;
        while (i < cn.len) {
            if (cn[i] == '$') {
                i += 1;
                const start = i;
                while (i < cn.len and cn[i] != '$' and cn[i] != '(') i += 1;
                const sname = cn[start..i];
                if (!first) try writer.print(" & ", .{});
                try writer.print("{s}(7 downto 1)", .{sname});
                first = false;
            } else i += 1;
        }
        try writer.print(";\n", .{});
    }

    // ROM lookups
    for (def.constants) |tbl| {
        const tbl_id = try sanitizeName(allocator, tbl.composed_name);
        defer allocator.free(tbl_id);
        const val_bits = try tableValueWidth(allocator, tbl);

        try writer.print("\n  -- ROM lookup for {s}\n", .{tbl.composed_name});
        try writer.print("  process({s}_key, complete) begin\n", .{tbl_id});
        try writer.print("    {s}_data  <= (others => '0');\n", .{tbl_id});
        try writer.print("    {s}_valid <= '0';\n", .{tbl_id});
        try writer.print("    if complete = '1' then\n", .{});
        try writer.print("      case {s}_key is\n", .{tbl_id});

        switch (tbl.kind) {
            .explicit => |entries| {
                var key_buf: [128]u8 = undefined;
                var val_buf: [64]u8 = undefined;
                for (entries) |entry| {
                    var key_pos: usize = 0;
                    for (entry.key) |ch| {
                        const dv: u64 = ch - '0';
                        const seg = binStr(key_buf[key_pos..], dv, DATA_WIDTH);
                        key_pos += seg.len;
                    }
                    const key_str = key_buf[0..key_pos];
                    const val_int = std.fmt.parseInt(u64, entry.value, 10) catch 0;
                    const val_str = binStr(&val_buf, val_int, val_bits);
                    try writer.print("        when \"{s}\" => {s}_data <= \"{s}\"; {s}_valid <= '1';\n", .{ key_str, tbl_id, val_str, tbl_id });
                }
            },
            .generate => |gen| {
                const entries = try enumerateGenerate(allocator, gen);
                defer allocator.free(entries);
                var key_buf: [128]u8 = undefined;
                var val_buf: [64]u8 = undefined;
                for (entries) |entry| {
                    var key_pos: usize = 0;
                    for (entry.input_values) |v| {
                        const seg = binStr(key_buf[key_pos..], @intCast(v), DATA_WIDTH);
                        key_pos += seg.len;
                    }
                    const key_str = key_buf[0..key_pos];
                    const val_str = binStr(&val_buf, @intCast(entry.output_value), val_bits);
                    try writer.print("        when \"{s}\" => {s}_data <= \"{s}\"; {s}_valid <= '1';\n", .{ key_str, tbl_id, val_str, tbl_id });
                }
            },
        }

        try writer.print("        when others => null;\n", .{});
        try writer.print("      end case;\n    end if;\n  end process;\n", .{});
    }

    // destination fills (outputs)
    try writer.print("\n  -- destination fills (outputs)\n", .{});
    for (def.resolution) |stmt| {
        switch (stmt) {
            .fill => |f| {
                if (!try writeContainedLookup(allocator, writer, def, f)) {
                    const tbl_id = try sanitizeName(allocator, f.expr);
                    defer allocator.free(tbl_id);
                    const dest_id = try sanitizeName(allocator, f.dest_name);
                    defer allocator.free(dest_id);
                    try writer.print("  {s} <= {s}_data & {s}_valid;\n", .{ dest_id, tbl_id, tbl_id });
                }
            },
            .invoke => |inv| {
                try writer.print("  -- TODO: component instantiation for {s}\n", .{inv.name});
            },
            .pure_value => |v| {
                try writer.print("  -- TODO: pure value expression {s} (contained-definition resolution not yet implemented)\n", .{v});
            },
        }
    }

    try writer.print("\nend rtl;\n", .{});

    for (def.contained) |contained| {
        if (std.ascii.isDigit(contained.name[0])) continue;
        try writer.print("\n", .{});
        try writeDefinition(allocator, writer, contained);
    }
}

fn writeContainedLookup(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
    fill: network.SourceFill,
) !bool {
    if (def.sources.len == 0 or def.contained.len == 0) return false;
    for (def.sources) |source| {
        if (std.mem.indexOf(u8, fill.expr, source.name) == null) return false;
    }

    for (def.contained) |row| {
        _ = std.fmt.parseInt(u64, row.name, 10) catch return false;
        if (row.resolution.len != 1) return false;
        switch (row.resolution[0]) {
            .pure_value => |value| {
                _ = std.fmt.parseInt(u64, value, 10) catch return false;
            },
            else => return false,
        }
    }

    try writer.print("  process(", .{});
    for (def.sources, 0..) |source, i| {
        if (i > 0) try writer.print(", ", .{});
        const source_id = try sanitizeName(allocator, source.name);
        defer allocator.free(source_id);
        try writer.print("{s}", .{source_id});
    }
    const dest_id = try sanitizeName(allocator, fill.dest_name);
    defer allocator.free(dest_id);
    try writer.print(", complete) begin\n" ++
        "    {s} <= (others => '0');\n" ++
        "    if complete = '1' then\n" ++
        "      case ", .{dest_id});
    // Rebuild the case expression from all source payloads.
    var first_source = true;
    for (def.sources) |source| {
        const source_id = try sanitizeName(allocator, source.name);
        defer allocator.free(source_id);
        if (!first_source) try writer.print(" & ", .{});
        try writer.print("{s}({d} downto 1)", .{ source_id, SIGNAL_WIDTH - 1 });
        first_source = false;
    }
    try writer.print(" is\n", .{});

    for (def.contained) |row| {
        const input = try std.fmt.parseInt(u64, row.name, 10);
        const output = switch (row.resolution[0]) {
            .pure_value => |value| try std.fmt.parseInt(u64, value, 10),
            else => unreachable,
        };
        const key_width = def.sources.len * DATA_WIDTH;
        var input_buf: [128]u8 = undefined;
        const input_bits = binStr(&input_buf, input, key_width);
        try writer.print("        when \"{s}\" => {s} <= data_value({d});\n", .{ input_bits, dest_id, output });
    }

    try writer.print("        when others => null;\n" ++
        "      end case;\n" ++
        "    end if;\n" ++
        "  end process;\n", .{});
    return true;
}

// ----------------------------------------------------------------
// Generate block evaluator
// ----------------------------------------------------------------

const GeneratedEntry = struct {
    input_values: []const i64,
    output_value: i64,
};

fn enumerateGenerate(
    allocator: std.mem.Allocator,
    gen: network.GenerateBlock,
) ![]const GeneratedEntry {
    var const_map = std.StringHashMap(i64).init(allocator);
    defer const_map.deinit();
    for (gen.constants) |c| try const_map.put(c.name, c.value);

    var entries: std.ArrayListUnmanaged(GeneratedEntry) = .empty;
    var var_map = std.StringHashMap(i64).init(allocator);
    defer var_map.deinit();

    const current_vals = try allocator.alloc(i64, gen.inputs.len);
    defer allocator.free(current_vals);

    try enumerateRecursive(allocator, gen, gen.inputs, current_vals, 0, &var_map, const_map, &entries);

    return entries.toOwnedSlice(allocator);
}

fn enumerateRecursive(
    allocator: std.mem.Allocator,
    gen: network.GenerateBlock,
    inputs: []const network.InputDecl,
    current_vals: []i64,
    depth: usize,
    var_map: *std.StringHashMap(i64),
    const_map: std.StringHashMap(i64),
    entries: *std.ArrayListUnmanaged(GeneratedEntry),
) !void {
    if (depth == inputs.len) {
        const result = try evalExpr(gen.expr, var_map.*, const_map);
        const clamped = @max(gen.output_min, @min(gen.output_max, result));
        const vals_copy = try allocator.dupe(i64, current_vals);
        try entries.append(allocator, .{
            .input_values = vals_copy,
            .output_value = clamped,
        });
        return;
    }
    const inp = inputs[depth];
    var v = inp.min;
    while (v <= inp.max) : (v += 1) {
        current_vals[depth] = v;
        try var_map.put(inp.name, v);
        try enumerateRecursive(allocator, gen, inputs, current_vals, depth + 1, var_map, const_map, entries);
    }
}

fn evalExpr(
    expr: *const network.Expr,
    variables: std.StringHashMap(i64),
    constants: std.StringHashMap(i64),
) !i64 {
    return switch (expr.kind) {
        .integer => expr.int_val,
        .variable => variables.get(expr.name) orelse 0,
        .constant => constants.get(expr.name) orelse 0,
        .binary => {
            const l = try evalExpr(expr.left.?, variables, constants);
            const r = try evalExpr(expr.right.?, variables, constants);
            return switch (expr.op) {
                .add => l + r,
                .sub => l - r,
                .mul => l * r,
                .div => if (r == 0) 0 else @divTrunc(l, r),
            };
        },
        .call => {
            if (std.mem.eql(u8, expr.func, "clamp")) {
                const val = try evalExpr(expr.args[0], variables, constants);
                const lo = try evalExpr(expr.args[1], variables, constants);
                const hi = try evalExpr(expr.args[2], variables, constants);
                return @max(lo, @min(hi, val));
            }
            if (std.mem.eql(u8, expr.func, "avg")) {
                var sum: i64 = 0;
                for (expr.args) |arg|
                    sum += try evalExpr(arg, variables, constants);
                return if (expr.args.len == 0) 0 else @divTrunc(sum, @as(i64, @intCast(expr.args.len)));
            }
            return 0;
        },
    };
}

// ----------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------

fn sanitizeName(allocator: std.mem.Allocator, composed: []const u8) ![]u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    for (composed) |c| {
        if (std.ascii.isAlphanumeric(c) or c == '_')
            try buf.append(allocator, c);
    }
    if (isVhdlReserved(buf.items)) {
        var prefixed: std.ArrayListUnmanaged(u8) = .empty;
        try prefixed.appendSlice(allocator, "ms_");
        try prefixed.appendSlice(allocator, buf.items);
        buf.deinit(allocator);
        return prefixed.toOwnedSlice(allocator);
    }
    return buf.toOwnedSlice(allocator);
}

fn placeName(allocator: std.mem.Allocator, place: network.Place) ![]u8 {
    if (place.group) |group| {
        var raw: std.ArrayListUnmanaged(u8) = .empty;
        try raw.appendSlice(allocator, "group");
        for (group.places) |member| {
            const member_name = try placeName(allocator, member);
            defer allocator.free(member_name);
            try raw.append(allocator, '_');
            try raw.appendSlice(allocator, member_name);
        }
        const result = try sanitizeName(allocator, raw.items);
        raw.deinit(allocator);
        return result;
    }
    return sanitizeName(allocator, place.name);
}

fn isVhdlReserved(name: []const u8) bool {
    const reserved = [_][]const u8{
        "abs",     "access",  "after",     "alias",  "all",        "and",    "architecture", "array",         "assert",    "attribute",
        "begin",   "block",   "body",      "buffer", "bus",        "case",   "component",    "configuration", "constant",  "disconnect",
        "else",    "elsif",   "end",       "entity", "exit",       "file",   "for",          "function",      "generate",  "generic",
        "group",   "guarded", "if",        "impure", "in",         "inout",  "is",           "label",         "library",   "linkage",
        "literal", "loop",    "map",       "mod",    "nand",       "new",    "next",         "nor",           "not",       "null",
        "of",      "on",      "open",      "or",     "others",     "out",    "package",      "port",          "postponed", "procedure",
        "process", "pure",    "range",     "record", "register",   "reject", "rem",          "report",        "return",    "rol",
        "ror",     "select",  "severity",  "signal", "shared",     "sla",    "sll",          "sra",           "srl",       "subtype",
        "then",    "to",      "transport", "type",   "unaffected", "units",  "until",        "use",           "variable",  "wait",
        "when",    "while",   "with",      "xnor",   "xor",
    };
    for (reserved) |keyword| {
        if (std.ascii.eqlIgnoreCase(name, keyword)) return true;
    }
    return false;
}

// count $ signs in composed name to determine key width
fn countSources(composed: []const u8) usize {
    var count: usize = 0;
    for (composed) |c| if (c == '$') {
        count += 1;
    };
    return count;
}

fn tableValueWidth(allocator: std.mem.Allocator, tbl: network.TableDef) !usize {
    var max_val: u64 = 0;
    switch (tbl.kind) {
        .explicit => |entries| {
            for (entries) |e| {
                const v = std.fmt.parseInt(u64, e.value, 10) catch 0;
                if (v > max_val) max_val = v;
            }
        },
        .generate => |gen| {
            _ = allocator;
            max_val = @intCast(@max(0, gen.output_max));
        },
    }
    if (max_val == 0) return 1;
    var bits: usize = 0;
    var v = max_val;
    while (v > 0) : (v >>= 1) bits += 1;
    return bits;
}

fn binStr(buf: []u8, val: u64, width: usize) []u8 {
    var i: usize = 0;
    while (i < width) : (i += 1) {
        const bit = (val >> @intCast(width - 1 - i)) & 1;
        buf[i] = if (bit == 1) '1' else '0';
    }
    return buf[0..width];
}
