// export_vhdl.zig
// VHDL emitter for MatterScript Invocation Language networks
//
// Port mapping (Fant authoritative grammar):
//   Definition source place  (name<>) → VHDL input  port  (tokens flow IN)
//   Definition destination place ($name) → VHDL output port (tokens flow OUT)
//
// Signal encoding:
//   signal[7:0] = { data[6:0], valid }
//   signal[0]   = valid bit  (1=DATA, 0=NULL)
//   signal[7:1] = 7-bit data payload (up to 127 distinct token values)

const std = @import("std");
const network = @import("network.zig");
const workspace = @import("../../common/workspace.zig");

const SIGNAL_WIDTH = 8;
const DATA_WIDTH = 7;

pub fn writeVhdlNetwork(
    io: std.Io,
    allocator: std.mem.Allocator,
    namespace: []const u8,
    net: network.Network,
    output_name: []const u8,
) !void {
    const output_path = try std.fmt.allocPrint(allocator, "../workspace/{s}/{s}", .{ namespace, output_name });
    defer allocator.free(output_path);

    var file = try std.Io.Dir.cwd().createFile(io, output_path, .{});
    defer file.close(io);

    var buffer: [65536]u8 = undefined;
    var writer = file.writer(io, &buffer);
    try write(allocator, &writer.interface, net);
    try writer.interface.flush();
}

pub fn write(allocator: std.mem.Allocator, writer: anytype, net: network.Network) !void {
    for (net.definitions) |def| {
        try writeDefinition(allocator, writer, def, "");
        try writer.print("\n", .{});
    }
}

fn writeDefinition(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
    scope: []const u8,
) !void {
    const def_id = try scopedDefinitionName(allocator, scope, def.name);
    defer allocator.free(def_id);
    try writer.print(
        \\-- generated by MatterScript IPL
        \\-- definition: {s}
        \\library ieee;
        \\use ieee.std_logic_1164.all;
        \\use ieee.numeric_std.all;
        \\use work.matterscript_ncl.all;
        \\
        \\
    , .{def.name});

    // entity
    try writer.print("entity {s} is\n  port(\n", .{def_id});
    try writer.print("    clk : in  std_logic;\n", .{});
    const boundary_count = boundaryCount(def.sources) + boundaryCount(def.destinations);
    try writer.print("    rst : in  std_logic{s}\n", .{if (boundary_count == 0) "" else ";"});

    // sources → inputs (tokens flow IN to the definition)
    var port_index: usize = 0;
    var port_names: std.ArrayListUnmanaged([]const u8) = .empty;
    for (def.sources) |src| {
        try writeBoundaryPorts(allocator, writer, src, "in", &port_index, boundary_count, &port_names);
    }

    // destinations → outputs (tokens flow OUT of the definition)
    for (def.destinations) |dest| {
        try writeBoundaryPorts(allocator, writer, dest, "out", &port_index, boundary_count, &port_names);
    }
    try writer.print("  );\nend {s};\n\n", .{def_id});

    // architecture
    try writer.print("architecture rtl of {s} is\n", .{def_id});

    // valid signals — one per source (input)
    for (def.sources) |src| {
        try writeBoundaryValidDeclarations(allocator, writer, src);
    }
    try writer.print("  signal complete   : std_logic;\n", .{});

    // per-table signals
    for (def.constants) |tbl| {
        const tbl_id = try sanitizeName(allocator, tbl.composed_name);
        defer allocator.free(tbl_id);
        const key_bits = countSources(tbl.composed_name) * DATA_WIDTH;
        const val_bits = try tableValueWidth(allocator, tbl);
        try writer.print("  signal {s}_key   : std_logic_vector({d} downto 0);\n", .{ tbl_id, key_bits - 1 });
        try writer.print("  signal {s}_data  : std_logic_vector({d} downto 0);\n", .{ tbl_id, val_bits - 1 });
        try writer.print("  signal {s}_valid : std_logic;\n", .{tbl_id});
    }

    var intermediate_names: std.ArrayListUnmanaged([]const u8) = .empty;
    for (def.resolution) |stmt| {
        switch (stmt) {
            .fill => |fill| {
                try writeIntermediateSignal(allocator, writer, def, &intermediate_names, fill.dest_name);
                try writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, fill.expr);
            },
            .invoke => |inv| {
                for (inv.outputs) |output| {
                    try writeIntermediatePlaceSignal(allocator, writer, def, &intermediate_names, output);
                }
                for (inv.args) |arg| {
                    try writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, arg);
                }
            },
            .pure_value => |value| try writeDollarReferenceSignals(allocator, writer, def, &intermediate_names, value),
        }
    }

    var component_names: std.ArrayListUnmanaged([]const u8) = .empty;
    for (def.resolution) |stmt| {
        if (stmt != .invoke) continue;
        const inv = stmt.invoke;
        var already_declared = false;
        for (component_names.items) |name| {
            if (std.ascii.eqlIgnoreCase(name, inv.name)) {
                already_declared = true;
                break;
            }
        }
        if (already_declared) continue;
        const name = try allocator.dupe(u8, inv.name);
        try component_names.append(allocator, name);
        const component_id = try invocationDefinitionName(allocator, def, scope, inv.name);
        defer allocator.free(component_id);
        try writeComponentDeclaration(writer, inv, component_id);
    }

    for (def.resolution, 0..) |stmt, invocation_index| {
        if (stmt != .invoke) continue;
        const inv = stmt.invoke;
        for (inv.args, 0..) |_, argument_index| {
            try writer.print("  signal invocation_{d}_arg_{d} : ncl_signal;\n", .{ invocation_index, argument_index });
        }
        for (inv.outputs, 0..) |output, output_index| {
            if (output.group == null and output.name.len != 0) continue;
            try writer.print("  signal invocation_{d}_output_{d} : ncl_signal;\n", .{ invocation_index, output_index });
        }
    }

    try writer.print("begin\n\n", .{});

    for (def.resolution, 0..) |stmt, invocation_index| {
        if (stmt != .invoke) continue;
        const inv = stmt.invoke;
        for (inv.args, 0..) |arg, argument_index| {
            try writeInvocationArgument(allocator, writer, invocation_index, argument_index, arg);
        }
        for (inv.outputs, 0..) |output, output_index| {
            if (output.group == null and output.name.len != 0) continue;
            try writer.print("  invocation_{d}_output_{d} <= null_value;\n", .{ invocation_index, output_index });
        }
        try writeInvocationInstance(allocator, writer, def, scope, inv, invocation_index);
    }

    // valid extraction from source places (inputs)
    try writer.print("  -- extract valid bits from source places (inputs)\n", .{});
    for (def.sources) |src| {
        try writeBoundaryValidAssignments(allocator, writer, src);
    }

    // completeness: AND of all source valids
    try writer.print("\n  -- complete when all source places are valid\n", .{});
    if (def.sources.len == 0) {
        try writer.print("  complete <= '1';\n", .{});
    } else {
        try writer.print("  complete <= ", .{});
        for (def.sources, 0..) |src, i| {
            if (i > 0) try writer.print(" and ", .{});
            try writeBoundaryValidExpression(allocator, writer, src);
        }
        try writer.print(";\n", .{});
    }

    // key composition
    for (def.constants) |tbl| {
        const tbl_id = try sanitizeName(allocator, tbl.composed_name);
        defer allocator.free(tbl_id);
        try writer.print("\n  -- key composition for {s}\n", .{tbl.composed_name});
        try writer.print("  {s}_key <= ", .{tbl_id});
        var i: usize = 0;
        var first = true;
        const cn = tbl.composed_name;
        while (i < cn.len) {
            if (cn[i] == '$') {
                i += 1;
                const start = i;
                while (i < cn.len and cn[i] != '$' and cn[i] != '(') i += 1;
                const sname = cn[start..i];
                if (!first) try writer.print(" & ", .{});
                try writer.print("{s}(7 downto 1)", .{sname});
                first = false;
            } else i += 1;
        }
        try writer.print(";\n", .{});
    }

    // ROM lookups
    for (def.constants) |tbl| {
        const tbl_id = try sanitizeName(allocator, tbl.composed_name);
        defer allocator.free(tbl_id);
        const val_bits = try tableValueWidth(allocator, tbl);

        try writer.print("\n  -- ROM lookup for {s}\n", .{tbl.composed_name});
        try writer.print("  process({s}_key, complete) begin\n", .{tbl_id});
        try writer.print("    {s}_data  <= (others => '0');\n", .{tbl_id});
        try writer.print("    {s}_valid <= '0';\n", .{tbl_id});
        try writer.print("    if complete = '1' then\n", .{});
        try writer.print("      case {s}_key is\n", .{tbl_id});

        switch (tbl.kind) {
            .explicit => |entries| {
                var key_buf: [128]u8 = undefined;
                var val_buf: [64]u8 = undefined;
                for (entries) |entry| {
                    var key_pos: usize = 0;
                    for (entry.key) |ch| {
                        const dv: u64 = ch - '0';
                        const seg = binStr(key_buf[key_pos..], dv, DATA_WIDTH);
                        key_pos += seg.len;
                    }
                    const key_str = key_buf[0..key_pos];
                    const val_int = std.fmt.parseInt(u64, entry.value, 10) catch 0;
                    const val_str = binStr(&val_buf, val_int, val_bits);
                    try writer.print("        when \"{s}\" => {s}_data <= \"{s}\"; {s}_valid <= '1';\n", .{ key_str, tbl_id, val_str, tbl_id });
                }
            },
            .generate => |gen| {
                const entries = try enumerateGenerate(allocator, gen);
                defer allocator.free(entries);
                var key_buf: [128]u8 = undefined;
                var val_buf: [64]u8 = undefined;
                for (entries) |entry| {
                    var key_pos: usize = 0;
                    for (entry.input_values) |v| {
                        const seg = binStr(key_buf[key_pos..], @intCast(v), DATA_WIDTH);
                        key_pos += seg.len;
                    }
                    const key_str = key_buf[0..key_pos];
                    const val_str = binStr(&val_buf, @intCast(entry.output_value), val_bits);
                    try writer.print("        when \"{s}\" => {s}_data <= \"{s}\"; {s}_valid <= '1';\n", .{ key_str, tbl_id, val_str, tbl_id });
                }
            },
        }

        try writer.print("        when others => null;\n", .{});
        try writer.print("      end case;\n    end if;\n  end process;\n", .{});
    }

    // destination fills (outputs)
    try writer.print("\n  -- destination fills (outputs)\n", .{});
    if (!try writeContainedLookupTable(allocator, writer, def)) {
        for (def.resolution) |stmt| {
            switch (stmt) {
                .fill => |f| {
                    const literal = std.fmt.parseInt(u64, std.mem.trim(u8, f.expr, " \t\r\n"), 10) catch null;
                    if (literal) |value| {
                        const dest_id = try sanitizeName(allocator, f.dest_name);
                        defer allocator.free(dest_id);
                        try writer.print("  {s} <= data_value({d});\n", .{ dest_id, value });
                    } else if (!try writeExpressionFill(allocator, writer, f)) {
                        const dest_id = try sanitizeName(allocator, f.dest_name);
                        defer allocator.free(dest_id);
                        try writer.print("  {s} <= null_value;\n", .{dest_id});
                    }
                },
                .invoke => |inv| {
                    _ = inv;
                },
                .pure_value => |v| {
                    try writer.print("  -- TODO: pure value expression {s} (not a recognized lookup-table shape)\n", .{v});
                },
            }
        }
    }
    
    try writer.print("\nend rtl;\n", .{});

    for (def.contained) |contained| {
        if (std.ascii.isDigit(contained.name[0])) continue;
        try writer.print("\n", .{});
        try writeDefinition(allocator, writer, contained, def_id);
    }
}

fn writeExpressionFill(
    allocator: std.mem.Allocator,
    writer: anytype,
    fill: network.SourceFill,
) !bool {
    const expression = std.mem.trim(u8, fill.expr, " \t\r\n");
    const dest_id = try sanitizeName(allocator, fill.dest_name);
    defer allocator.free(dest_id);

    if (expression.len > 1 and expression[0] == '$') {
        var end = expression.len;
        if (std.mem.indexOfScalar(u8, expression, '(')) |open| end = open;
        const source_id = try sanitizeName(allocator, expression[1..end]);
        defer allocator.free(source_id);
        try writer.print("  {s} <= {s};\n", .{ dest_id, source_id });
        return true;
    }

    if (std.mem.startsWith(u8, expression, "Equal(")) {
        const dollar = std.mem.indexOfScalar(u8, expression, '$') orelse return false;
        const comma = std.mem.indexOfScalarPos(u8, expression, dollar, ',') orelse return false;
        const source_id = try sanitizeName(allocator, expression[dollar + 1 .. comma]);
        defer allocator.free(source_id);
        const value_end = std.mem.indexOfScalarPos(u8, expression, comma + 1, ')') orelse return false;
        const value_text = std.mem.trim(u8, expression[comma + 1 .. value_end], " \t\r\n");
        const value = std.fmt.parseInt(u64, value_text, 10) catch return false;
        try writer.print("  process({s}) begin\n", .{source_id});
        try writer.print("    {s} <= null_value;\n", .{dest_id});
        try writer.print("    if is_data({s}) and payload({s}) = std_logic_vector(to_unsigned({d}, DATA_WIDTH)) then\n", .{ source_id, source_id, value });
        try writer.print("      {s} <= data_value(1);\n", .{dest_id});
        try writer.print("    elsif is_data({s}) then\n", .{source_id});
        try writer.print("      {s} <= data_value(0);\n", .{dest_id});
        try writer.print("    end if;\n  end process;\n", .{});
        return true;
    }

    return false;
}

fn writeInvocationArgument(
    allocator: std.mem.Allocator,
    writer: anytype,
    invocation_index: usize,
    argument_index: usize,
    argument: []const u8,
) !void {
    const signal_name = try std.fmt.allocPrint(allocator, "invocation_{d}_arg_{d}", .{ invocation_index, argument_index });
    defer allocator.free(signal_name);
    const trimmed = std.mem.trim(u8, argument, " \t\r\n");
    if (trimmed.len > 1 and trimmed[0] == '$' and std.mem.indexOfScalar(u8, trimmed[1..], '$') == null) {
        const source_id = try sanitizeName(allocator, trimmed[1..]);
        defer allocator.free(source_id);
        try writer.print("  {s} <= {s};\n", .{ signal_name, source_id });
    } else if (std.fmt.parseInt(u64, trimmed, 10)) |value| {
        try writer.print("  {s} <= data_value({d});\n", .{ signal_name, value });
    } else |_| {
        try writer.print("  {s} <= null_value;\n", .{signal_name});
    }
}

fn writeInvocationInstance(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
    scope: []const u8,
    inv: network.Invocation,
    invocation_index: usize,
) !void {
    const component_id = try invocationDefinitionName(allocator, def, scope, inv.name);
    defer allocator.free(component_id);
    try writer.print("  invocation_{d} : {s} port map (clk => clk, rst => rst", .{ invocation_index, component_id });
    for (inv.args, 0..) |_, argument_index| {
        try writer.print(", arg_{d} => invocation_{d}_arg_{d}", .{ argument_index, invocation_index, argument_index });
    }
    for (inv.outputs, 0..) |output, output_index| {
        if (output.group != null or output.name.len == 0) {
            try writer.print(", output_{d} => invocation_{d}_output_{d}", .{ output_index, invocation_index, output_index });
        } else {
            const output_id = try placeName(allocator, output);
            defer allocator.free(output_id);
            try writer.print(", output_{d} => {s}", .{ output_index, output_id });
        }
    }
    try writer.print(");\n", .{});
}

fn scopedDefinitionName(
    allocator: std.mem.Allocator,
    scope: []const u8,
    name: []const u8,
) ![]u8 {
    if (scope.len == 0) return sanitizeName(allocator, name);
    const local_name = try sanitizeName(allocator, name);
    defer allocator.free(local_name);
    return std.fmt.allocPrint(allocator, "{s}_{s}", .{ scope, local_name });
}

fn invocationDefinitionName(
    allocator: std.mem.Allocator,
    def: network.Definition,
    scope: []const u8,
    name: []const u8,
) ![]u8 {
    for (def.contained) |contained| {
        if (std.ascii.eqlIgnoreCase(contained.name, name)) {
            return scopedDefinitionName(allocator, scope, name);
        }
    }
    return sanitizeName(allocator, name);
}

fn writeComponentDeclaration(
    writer: anytype,
    inv: network.Invocation,
    component_id: []const u8,
) !void {
    try writer.print("  component {s}\n    port(\n", .{component_id});
    try writer.print("      clk : in std_logic;\n      rst : in std_logic", .{});
    const port_count = inv.args.len + inv.outputs.len;
    if (port_count > 0) try writer.print(";", .{});
    try writer.print("\n", .{});

    for (inv.args, 0..) |_, i| {
        try writer.print("      arg_{d} : in ncl_signal{s}\n", .{ i, if (i + 1 == port_count) "" else ";" });
    }
    for (inv.outputs, 0..) |_, i| {
        try writer.print("      output_{d} : out ncl_signal{s}\n", .{ i, if (i + inv.args.len + 1 == port_count) "" else ";" });
    }
    try writer.print("    );\n  end component;\n\n", .{});
}

fn boundaryCount(places: []const network.Place) usize {
    var count: usize = 0;
    for (places) |place| count += placeBoundaryCount(place);
    return count;
}

fn placeBoundaryCount(place: network.Place) usize {
    const group = place.group orelse return 1;
    if (group.kind == .bundle) return 1;
    return boundaryCount(group.places);
}

fn writeBoundaryPorts(
    allocator: std.mem.Allocator,
    writer: anytype,
    place: network.Place,
    direction: []const u8,
    index: *usize,
    total: usize,
    names: *std.ArrayListUnmanaged([]const u8),
) !void {
    if (place.group) |group| {
        if (group.kind == .mutex) {
            for (group.places) |member| {
                try writeBoundaryPorts(allocator, writer, member, direction, index, total, names);
            }
            return;
        }
    }
    const base_id = try placeName(allocator, place);
    defer allocator.free(base_id);
    const id = try uniqueVhdlName(allocator, names.items, base_id);
    defer allocator.free(id);
    try names.append(allocator, try allocator.dupe(u8, id));
    index.* += 1;
    try writer.print("    {s} : {s} std_logic_vector({d} downto 0){s}\n", .{
        id, direction, SIGNAL_WIDTH - 1, if (index.* == total) "" else ";",
    });
}

fn uniqueVhdlName(
    allocator: std.mem.Allocator,
    names: []const []const u8,
    base: []const u8,
) ![]u8 {
    var suffix: usize = 0;
    while (true) : (suffix += 1) {
        const candidate = if (suffix == 0)
            try allocator.dupe(u8, base)
        else
            try std.fmt.allocPrint(allocator, "{s}_{d}", .{ base, suffix });
        var collision = false;
        for (names) |name| {
            if (std.ascii.eqlIgnoreCase(name, candidate)) {
                collision = true;
                break;
            }
        }
        if (!collision) return candidate;
        allocator.free(candidate);
    }
}

fn writeBoundaryValidDeclarations(
    allocator: std.mem.Allocator,
    writer: anytype,
    place: network.Place,
) !void {
    if (place.group) |group| {
        if (group.kind == .mutex) {
            for (group.places) |member| try writeBoundaryValidDeclarations(allocator, writer, member);
            return;
        }
    }
    const id = try placeName(allocator, place);
    defer allocator.free(id);
    try writer.print("  signal {s}_valid : std_logic;\n", .{id});
}

fn writeBoundaryValidAssignments(
    allocator: std.mem.Allocator,
    writer: anytype,
    place: network.Place,
) !void {
    if (place.group) |group| {
        if (group.kind == .mutex) {
            for (group.places) |member| try writeBoundaryValidAssignments(allocator, writer, member);
            return;
        }
    }
    const id = try placeName(allocator, place);
    defer allocator.free(id);
    try writer.print("  {s}_valid <= {s}(0);\n", .{ id, id });
}

fn writeBoundaryValidExpression(
    allocator: std.mem.Allocator,
    writer: anytype,
    place: network.Place,
) !void {
    if (place.group) |group| {
        if (group.kind == .mutex) {
            try writer.print("(", .{});
            for (group.places, 0..) |member, i| {
                if (i > 0) try writer.print(" or ", .{});
                try writeBoundaryValidExpression(allocator, writer, member);
            }
            try writer.print(")", .{});
            return;
        }
    }
    const id = try placeName(allocator, place);
    defer allocator.free(id);
    try writer.print("{s}_valid", .{id});
}

fn writeIntermediatePlaceSignal(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
    names: *std.ArrayListUnmanaged([]const u8),
    place: network.Place,
) !void {
    const name = try placeName(allocator, place);
    defer allocator.free(name);
    try writeIntermediateSignal(allocator, writer, def, names, name);
}

fn writeIntermediateSignal(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
    names: *std.ArrayListUnmanaged([]const u8),
    raw_name: []const u8,
) !void {
    if (raw_name.len == 0 or isDefinitionPort(def, raw_name)) return;
    for (names.items) |name| if (std.ascii.eqlIgnoreCase(name, raw_name)) return;
    try names.append(allocator, try allocator.dupe(u8, raw_name));
    const id = try sanitizeName(allocator, raw_name);
    defer allocator.free(id);
    try writer.print("  signal {s} : ncl_signal;\n", .{id});
}

fn writeDollarReferenceSignals(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
    names: *std.ArrayListUnmanaged([]const u8),
    expression: []const u8,
) !void {
    var i: usize = 0;
    while (i < expression.len) {
        if (expression[i] != '$') {
            i += 1;
            continue;
        }
        i += 1;
        const start = i;
        while (i < expression.len and (std.ascii.isAlphanumeric(expression[i]) or expression[i] == '_')) i += 1;
        if (i > start) try writeIntermediateSignal(allocator, writer, def, names, expression[start..i]);
    }
}

fn isDefinitionPort(def: network.Definition, name: []const u8) bool {
    for (def.sources) |place| if (std.ascii.eqlIgnoreCase(place.name, name)) return true;
    for (def.destinations) |place| if (std.ascii.eqlIgnoreCase(place.name, name)) return true;
    return false;
}

/// Builds one symbol table shared across an ENTIRE contained-lookup
/// definition — every comma-separated key segment in every row's
/// name, and every row's own value (a bare pure_value, or each named
/// fill's expr), all interned into the same table. Sharing it across
/// the whole definition (not per-destination) matters for state
/// machines: "S1" must encode to the same integer whether it appears
/// in a key segment or a fill value, since a destination's output can
/// feed back as a future invocation's source.
fn buildSharedSymbolTable(
    allocator: std.mem.Allocator,
    contained: []const network.Definition,
) !std.ArrayListUnmanaged([]const u8) {
    var symbols: std.ArrayListUnmanaged([]const u8) = .empty;
    for (contained) |row| {
        var it = std.mem.splitScalar(u8, row.name, ',');
        while (it.next()) |seg| {
            _ = try internSymbol(&symbols, allocator, std.mem.trim(u8, seg, " \t\r\n"));
        }
        for (row.resolution) |stmt| {
            const value_text = switch (stmt) {
                .pure_value => |v| v,
                .fill => |f| f.expr,
                .invoke => continue,
            };
            _ = try internSymbol(&symbols, allocator, std.mem.trim(u8, value_text, " \t\r\n"));
        }
    }
    return symbols;
}

/// Emits one ROM/case-select for a single outer destination.
/// `anonymous` selects how to read each row's value: true means every
/// row is a single bare pure_value (OR/AND/NOT's shape) and
/// `dest_name` is fixed externally (the triggering fill's own
/// destination); false means each row may carry a named fill for
/// `dest_name` specifically (TAG-136's shape) — a row missing a fill
/// for this destination is simply skipped, correctly leaving that
/// case to `others` per Fant's Occasional Output (§12.5.6).
fn writeLookupCaseBlock(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
    dest_name: []const u8,
    symbols: *std.ArrayListUnmanaged([]const u8),
    anonymous: bool,
) !void {
    const dest_id = try sanitizeName(allocator, dest_name);
    defer allocator.free(dest_id);

    try writer.print("\n  -- lookup for {s}\n", .{dest_name});
    try writer.print("  process(", .{});
    for (def.sources, 0..) |source, i| {
        if (i > 0) try writer.print(", ", .{});
        const source_id = try sanitizeName(allocator, source.name);
        defer allocator.free(source_id);
        try writer.print("{s}", .{source_id});
    }
    try writer.print(", complete) begin\n" ++
        "    {s} <= null_value;\n" ++
        "    if complete = '1' then\n" ++
        "      case ", .{dest_id});
    for (def.sources, 0..) |source, i| {
        const source_id = try sanitizeName(allocator, source.name);
        defer allocator.free(source_id);
        if (i > 0) try writer.print(" & ", .{});
        try writer.print("{s}({d} downto 1)", .{ source_id, SIGNAL_WIDTH - 1 });
    }
    try writer.print(" is\n", .{});

    for (def.contained) |row| {
        var value_text: ?[]const u8 = null;
        if (anonymous) {
            value_text = row.resolution[0].pure_value;
        } else {
            for (row.resolution) |stmt| {
                if (stmt == .fill and std.mem.eql(u8, stmt.fill.dest_name, dest_name)) {
                    value_text = stmt.fill.expr;
                    break;
                }
            }
        }
        const vt = value_text orelse continue;

        var key_buf: [128]u8 = undefined;
        var key_pos: usize = 0;
        var it = std.mem.splitScalar(u8, row.name, ',');
        while (it.next()) |seg| {
            const seg_value = try internSymbol(symbols, allocator, std.mem.trim(u8, seg, " \t\r\n"));
            const piece = binStr(key_buf[key_pos..], seg_value, DATA_WIDTH);
            key_pos += piece.len;
        }
        const key_str = key_buf[0..key_pos];

        const out_value = try internSymbol(symbols, allocator, std.mem.trim(u8, vt, " \t\r\n"));
        try writer.print("        when \"{s}\" => {s} <= data_value({d});\n", .{ key_str, dest_id, out_value });
    }

    try writer.print("        when others => null;\n" ++
        "      end case;\n" ++
        "    end if;\n" ++
        "  end process;\n", .{});
}

/// Detects which of the two contained-lookup shapes (if either)
/// applies to `def`, and dispatches to writeLookupCaseBlock
/// accordingly. See writeLookupCaseBlock's doc comment for the shapes.
fn writeContainedLookupTable(
    allocator: std.mem.Allocator,
    writer: anytype,
    def: network.Definition,
) !bool {
    if (def.sources.len == 0 or def.contained.len == 0) return false;

    for (def.contained) |row| {
        if (row.sources.len != 0 or row.destinations.len != 0) return false;
        var seg_count: usize = 1;
        for (row.name) |ch| {
            if (ch == ',') seg_count += 1;
        }
        if (seg_count != def.sources.len) return false;
        if (row.resolution.len == 0) return false;
    }

    var all_anonymous = true;
    var all_structured = true;
    for (def.contained) |row| {
        if (!(row.resolution.len == 1 and row.resolution[0] == .pure_value)) all_anonymous = false;
        for (row.resolution) |stmt| {
            if (stmt != .fill) all_structured = false;
        }
    }
    if (!all_anonymous and !all_structured) return false;

    var symbols = try buildSharedSymbolTable(allocator, def.contained);

    if (symbols.items.len > 0) {
        try writer.print("  -- symbol encoding: ", .{});
        for (symbols.items, 0..) |sym, i| {
            if (i > 0) try writer.print(", ", .{});
            try writer.print("{s}={d}", .{ sym, i });
        }
        try writer.print("\n", .{});
    }

    if (all_anonymous) {
        for (def.resolution) |stmt| {
            if (stmt != .fill) continue;
            const f = stmt.fill;
            var mentions_all = true;
            for (def.sources) |s| {
                if (std.mem.indexOf(u8, f.expr, s.name) == null) mentions_all = false;
            }
            if (!mentions_all) continue;
            try writeLookupCaseBlock(allocator, writer, def, f.dest_name, &symbols, true);
            return true;
        }
        return false;
    }

    var covered: std.ArrayListUnmanaged([]const u8) = .empty;
    for (def.contained) |row| {
        for (row.resolution) |stmt| {
            const dname = stmt.fill.dest_name;
            var have = false;
            for (covered.items) |c| {
                if (std.mem.eql(u8, c, dname)) {
                    have = true;
                    break;
                }
            }
            if (!have) try covered.append(allocator, dname);
        }
    }
    for (covered.items) |dest_name| {
        try writeLookupCaseBlock(allocator, writer, def, dest_name, &symbols, false);
    }
    return true;
}

fn internSymbol(list: *std.ArrayListUnmanaged([]const u8), allocator: std.mem.Allocator, token: []const u8) !u64 {
    if (std.fmt.parseInt(u64, token, 10)) |n| return n else |_| {}
    for (list.items, 0..) |existing, i| {
        if (std.mem.eql(u8, existing, token)) return @intCast(i);
    }
    try list.append(allocator, try allocator.dupe(u8, token));
    return @intCast(list.items.len - 1);
}


// ----------------------------------------------------------------
// Generate block evaluator
// ----------------------------------------------------------------

const GeneratedEntry = struct {
    input_values: []const i64,
    output_value: i64,
};

fn enumerateGenerate(
    allocator: std.mem.Allocator,
    gen: network.GenerateBlock,
) ![]const GeneratedEntry {
    var const_map = std.StringHashMap(i64).init(allocator);
    defer const_map.deinit();
    for (gen.constants) |c| try const_map.put(c.name, c.value);

    var entries: std.ArrayListUnmanaged(GeneratedEntry) = .empty;
    var var_map = std.StringHashMap(i64).init(allocator);
    defer var_map.deinit();

    const current_vals = try allocator.alloc(i64, gen.inputs.len);
    defer allocator.free(current_vals);

    try enumerateRecursive(allocator, gen, gen.inputs, current_vals, 0, &var_map, const_map, &entries);

    return entries.toOwnedSlice(allocator);
}

fn enumerateRecursive(
    allocator: std.mem.Allocator,
    gen: network.GenerateBlock,
    inputs: []const network.InputDecl,
    current_vals: []i64,
    depth: usize,
    var_map: *std.StringHashMap(i64),
    const_map: std.StringHashMap(i64),
    entries: *std.ArrayListUnmanaged(GeneratedEntry),
) !void {
    if (depth == inputs.len) {
        const result = try evalExpr(gen.expr, var_map.*, const_map);
        const clamped = @max(gen.output_min, @min(gen.output_max, result));
        const vals_copy = try allocator.dupe(i64, current_vals);
        try entries.append(allocator, .{
            .input_values = vals_copy,
            .output_value = clamped,
        });
        return;
    }
    const inp = inputs[depth];
    var v = inp.min;
    while (v <= inp.max) : (v += 1) {
        current_vals[depth] = v;
        try var_map.put(inp.name, v);
        try enumerateRecursive(allocator, gen, inputs, current_vals, depth + 1, var_map, const_map, entries);
    }
}

fn evalExpr(
    expr: *const network.Expr,
    variables: std.StringHashMap(i64),
    constants: std.StringHashMap(i64),
) !i64 {
    return switch (expr.kind) {
        .integer => expr.int_val,
        .variable => variables.get(expr.name) orelse 0,
        .constant => constants.get(expr.name) orelse 0,
        .binary => {
            const l = try evalExpr(expr.left.?, variables, constants);
            const r = try evalExpr(expr.right.?, variables, constants);
            return switch (expr.op) {
                .add => l + r,
                .sub => l - r,
                .mul => l * r,
                .div => if (r == 0) 0 else @divTrunc(l, r),
            };
        },
        .call => {
            if (std.mem.eql(u8, expr.func, "clamp")) {
                const val = try evalExpr(expr.args[0], variables, constants);
                const lo = try evalExpr(expr.args[1], variables, constants);
                const hi = try evalExpr(expr.args[2], variables, constants);
                return @max(lo, @min(hi, val));
            }
            if (std.mem.eql(u8, expr.func, "avg")) {
                var sum: i64 = 0;
                for (expr.args) |arg|
                    sum += try evalExpr(arg, variables, constants);
                return if (expr.args.len == 0) 0 else @divTrunc(sum, @as(i64, @intCast(expr.args.len)));
            }
            return 0;
        },
    };
}

// ----------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------

fn sanitizeName(allocator: std.mem.Allocator, composed: []const u8) ![]u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    for (composed) |c| {
        if (std.ascii.isAlphanumeric(c) or c == '_')
            try buf.append(allocator, c);
    }
    if (isVhdlReserved(buf.items)) {
        var prefixed: std.ArrayListUnmanaged(u8) = .empty;
        try prefixed.appendSlice(allocator, "ms_");
        try prefixed.appendSlice(allocator, buf.items);
        buf.deinit(allocator);
        return prefixed.toOwnedSlice(allocator);
    }
    return buf.toOwnedSlice(allocator);
}

fn placeName(allocator: std.mem.Allocator, place: network.Place) ![]u8 {
    if (place.group) |group| {
        var raw: std.ArrayListUnmanaged(u8) = .empty;
        try raw.appendSlice(allocator, "group");
        if (group.places.len == 0) {
            if (place.content) |content| try raw.appendSlice(allocator, content);
        }
        for (group.places) |member| {
            const member_name = try placeName(allocator, member);
            defer allocator.free(member_name);
            try raw.append(allocator, '_');
            try raw.appendSlice(allocator, member_name);
        }
        const result = try sanitizeName(allocator, raw.items);
        raw.deinit(allocator);
        return result;
    }
    return sanitizeName(allocator, place.name);
}

fn isVhdlReserved(name: []const u8) bool {
    const reserved = [_][]const u8{
        "abs",     "access",  "after",     "alias",  "all",        "and",    "architecture", "array",         "assert",    "attribute",
        "begin",   "block",   "body",      "buffer", "bus",        "case",   "component",    "configuration", "constant",  "disconnect",
        "else",    "elsif",   "end",       "entity", "exit",       "file",   "for",          "function",      "generate",  "generic",
        "group",   "guarded", "if",        "impure", "in",         "inout",  "is",           "label",         "library",   "linkage",
        "literal", "loop",    "map",       "mod",    "nand",       "new",    "next",         "nor",           "not",       "null",
        "of",      "on",      "open",      "or",     "others",     "out",    "package",      "port",          "postponed", "procedure",
        "process", "pure",    "range",     "record", "register",   "reject", "rem",          "report",        "return",    "rol",
        "ror",     "select",  "severity",  "signal", "shared",     "sla",    "sll",          "sra",           "srl",       "subtype",
        "then",    "to",      "transport", "type",   "unaffected", "units",  "until",        "use",           "variable",  "wait",
        "when",    "while",   "with",      "xnor",   "xor",
    };
    for (reserved) |keyword| {
        if (std.ascii.eqlIgnoreCase(name, keyword)) return true;
    }
    return false;
}

// count $ signs in composed name to determine key width
fn countSources(composed: []const u8) usize {
    var count: usize = 0;
    for (composed) |c| if (c == '$') {
        count += 1;
    };
    return count;
}

fn tableValueWidth(allocator: std.mem.Allocator, tbl: network.TableDef) !usize {
    var max_val: u64 = 0;
    switch (tbl.kind) {
        .explicit => |entries| {
            for (entries) |e| {
                const v = std.fmt.parseInt(u64, e.value, 10) catch 0;
                if (v > max_val) max_val = v;
            }
        },
        .generate => |gen| {
            _ = allocator;
            max_val = @intCast(@max(0, gen.output_max));
        },
    }
    if (max_val == 0) return 1;
    var bits: usize = 0;
    var v = max_val;
    while (v > 0) : (v >>= 1) bits += 1;
    return bits;
}

fn binStr(buf: []u8, val: u64, width: usize) []u8 {
    var i: usize = 0;
    while (i < width) : (i += 1) {
        const bit = (val >> @intCast(width - 1 - i)) & 1;
        buf[i] = if (bit == 1) '1' else '0';
    }
    return buf[0..width];
}
